// Copyright 2026 Lablup Inc. Licensed under the Apache License, Version 2.0.
// Activity copy. Metric labels are keyed as activity.metric.<metric_name>; every
// entry is mirrored in tests/fixtures/webui/strings.json.
export const activityStrings = [
  { key: 'activity.intro', en: 'Operations and runtime observations. Browsing never loads a model.', ko: '작업과 런타임 관측입니다. 조회는 모델을 로드하지 않습니다.', test_id: 'activity-intro' },
  { key: 'activity.session', en: 'History belongs to this server session: up to 200 terminal operations for one hour. A restart clears it; reconnect reconciles the authoritative snapshot.', ko: '기록은 서버 세션에 속합니다. 완료 작업 최대 200개를 한 시간 보관하며, 재시작 시 초기화하고 재연결 시 서버 상태와 대조합니다.', test_id: 'activity-session' },
  { key: 'activity.export', en: 'Export sanitized diagnostics', ko: '민감 정보 없는 진단 내보내기', test_id: 'activity-export' },
  { key: 'activity.refresh', en: 'Refresh observations', ko: '관측 새로고침', test_id: 'activity-refresh' },
  { key: 'activity.stale', en: 'Observations are stale. Last values are not current measurements.', ko: '관측이 최신 상태가 아닙니다. 마지막 값은 현재 측정값이 아닙니다.', test_id: 'activity-stale' },
  { key: 'activity.updated', en: 'Last successful snapshot', ko: '마지막 성공 스냅샷', test_id: 'activity-updated' },
  { key: 'activity.pending', en: 'Waiting for the first snapshot', ko: '첫 스냅샷을 기다리는 중', test_id: 'activity-pending' },
  { key: 'activity.operations', en: 'Operations', ko: '작업', test_id: 'activity-operations' },
  { key: 'activity.operations.counts', en: 'Operations: {active} active · {failed} failed', ko: '작업: {active} 진행 중 · {failed} 실패', test_id: 'activity-operations-counts' },
  { key: 'activity.operations.empty.title', en: 'No operations in this session', ko: '이 세션의 작업 없음', test_id: 'activity-operations-empty-title' },
  { key: 'activity.operations.empty.body', en: 'Explicit downloads, loads, drains and removals will appear here.', ko: '명시적인 다운로드, 로드, 드레인 및 삭제 작업이 표시됩니다.', test_id: 'activity-operations-empty-body' },
  { key: 'activity.cancel', en: 'Request cancellation', ko: '취소 요청', test_id: 'activity-cancel' },
  { key: 'activity.cancelling', en: 'Cancellation requested; waiting for worker acknowledgement.', ko: '취소 요청됨. 작업자 확인을 기다립니다.', test_id: 'activity-cancelling' },
  { key: 'activity.failure', en: 'The action failed. Check its state and refresh before retrying from Models.', ko: '작업에 실패했습니다. 상태를 확인하고 새로고침한 후 모델 화면에서 재시도하세요.', test_id: 'activity-failure' },
  { key: 'activity.cancel_failed', en: 'Cancellation could not be confirmed. Refresh to reconcile the operation.', ko: '취소를 확인하지 못했습니다. 새로고침하여 작업 상태를 대조하세요.', test_id: 'activity-cancel-failed' },
  { key: 'activity.cancel_unsupported', en: 'Cancellation is unavailable for this operation; worker execution is not interrupted.', ko: '이 작업은 취소할 수 없습니다. 실행 중인 작업자를 강제로 중단하지 않습니다.', test_id: 'activity-cancel-unsupported' },
  { key: 'activity.runtime', en: 'Selected model runtime', ko: '선택한 모델 런타임', test_id: 'activity-runtime' },
  { key: 'activity.select', en: 'Select a model to observe', ko: '관측할 모델 선택', test_id: 'activity-select' },
  { key: 'activity.select_body', en: 'Use the model picker. Selection does not load the model.', ko: '모델 선택기를 사용하세요. 선택만으로 모델을 로드하지 않습니다.', test_id: 'activity-select-body' },
  { key: 'activity.unavailable', en: 'N/A — no authoritative sample is available.', ko: 'N/A — 확인된 관측값이 없습니다.', test_id: 'activity-unavailable' },
  { key: 'activity.not_available', en: 'N/A', ko: 'N/A', test_id: 'activity-not-available' },
  { key: 'activity.memory', en: 'Memory figures have separate scopes and may overlap. Do not add process, allocator, device and cache values together.', ko: '메모리 수치는 서로 다른 범위이며 중복될 수 있습니다. 프로세스, 할당자, 장치 및 캐시 값을 합산하지 마세요.', test_id: 'activity-memory' },
  { key: 'activity.timing', en: 'Server counters are not browser TTFT. Chat shows request-send to first reasoning/content delta separately; no rendered word counts are used as tokens.', ko: '서버 카운터는 브라우저 TTFT가 아닙니다. 채팅은 요청 전송부터 첫 추론/내용 델타까지 별도로 표시하며, 단어 수를 토큰으로 사용하지 않습니다.', test_id: 'activity-timing' },
  { key: 'activity.slots', en: 'Request slots', ko: '요청 슬롯', test_id: 'activity-slots' },
  { key: 'activity.slot', en: 'Slot', ko: '슬롯', test_id: 'activity-slot' },
  { key: 'activity.processing', en: 'Processing', ko: '처리 중', test_id: 'activity-processing' },
  { key: 'activity.idle', en: 'Idle', ko: '유휴', test_id: 'activity-idle' },
  { key: 'activity.context', en: 'Request context window', ko: '요청 컨텍스트 한도', test_id: 'activity-context' },
  { key: 'activity.pool', en: 'Shared pool context', ko: '공유 풀 컨텍스트', test_id: 'activity-pool' },
  { key: 'activity.parallel', en: 'Effective parallelism', ko: '실제 병렬도', test_id: 'activity-parallel' },
  { key: 'activity.context_line', en: '{context}: {request} tokens · {pool}: {shared} tokens', ko: '{context}: {request} 토큰 · {pool}: {shared} 토큰', test_id: 'activity-context-line' },
  { key: 'activity.no_context', en: 'N/A — context denominator is unknown; no occupancy percentage is inferred.', ko: 'N/A — 컨텍스트 분모를 알 수 없어 점유율을 추정하지 않습니다.', test_id: 'activity-no-context' },
  { key: 'activity.slot_progress', en: '{used} / {total} tokens', ko: '{used} / {total} 토큰', test_id: 'activity-slot-progress' },
  { key: 'activity.slot_tokens', en: 'Accepted decode: {decoded} tokens · Cached prompt: {cached} tokens', ko: '수락된 디코드: {decoded} 토큰 · 캐시된 프롬프트: {cached} 토큰', test_id: 'activity-slot-tokens' },
  { key: 'activity.history.show', en: 'Show recent history', ko: '최근 기록 보기', test_id: 'activity-history-show' },
  { key: 'activity.history.hide', en: 'Hide recent history', ko: '최근 기록 숨기기', test_id: 'activity-history-hide' },
  { key: 'activity.history.note', en: 'Five-minute in-memory history, at most 150 two-second samples. Hidden tabs stop observation; gaps and counter resets are not interpolated.', ko: '메모리 내 5분 기록이며 2초 간격 최대 150개입니다. 숨겨진 탭은 관측을 중지합니다. 공백과 카운터 초기화를 보간하지 않습니다.', test_id: 'activity-history-note' },
  { key: 'activity.chart.label', en: 'Active requests: discrete observations over the last five minutes', ko: '활성 요청: 최근 5분 동안의 개별 관측값', test_id: 'activity-chart-label' },
  { key: 'activity.chart.title', en: 'Active requests (requests, selected model)', ko: '활성 요청 (요청 수, 선택한 모델)', test_id: 'activity-chart-title' },
  { key: 'activity.chart.point', en: '{value} requests', ko: '요청 {value}개', test_id: 'activity-chart-point' },
  { key: 'activity.scope', en: 'Scope', ko: '범위', test_id: 'activity-scope' },
  { key: 'activity.observed', en: 'Observed at', ko: '관측 시각', test_id: 'activity-observed' },
  { key: 'activity.metric_details', en: 'All measurements and sources', ko: '전체 측정값과 출처', test_id: 'activity-metric-details' },
  { key: 'activity.unavailable_count', en: 'Unavailable measurements', ko: '사용할 수 없는 측정값', test_id: 'activity-unavailable-count' },
  { key: 'activity.unavailable_reason', en: 'Some sources are disabled or do not publish an authoritative sample. Expand details for individual reasons.', ko: '일부 출처가 비활성화되었거나 확인된 관측값을 제공하지 않습니다. 상세 내용을 펼쳐 개별 사유를 확인하세요.', test_id: 'activity-unavailable-reason' },
  { key: 'activity.no_primary', en: 'No primary request counters are available.', ko: '사용 가능한 주요 요청 카운터가 없습니다.', test_id: 'activity-no-primary' },
  { key: 'activity.bytes', en: 'bytes downloaded', ko: '다운로드 바이트', test_id: 'activity-bytes' },
  { key: 'activity.download_progress', en: '{completed} / {total} bytes', ko: '{completed} / {total} 바이트', test_id: 'activity-download-progress' },
  { key: 'activity.details', en: 'Operation details', ko: '작업 상세', test_id: 'activity-details' },
  { key: 'activity.status', en: 'Operation status', ko: '작업 상태', test_id: 'activity-status' },
  { key: 'activity.unknown_time', en: 'Unknown', ko: '알 수 없음', test_id: 'activity-unknown-time' },
  { key: 'activity.metric.active_requests', en: 'Active requests', ko: '활성 요청', test_id: 'activity-metric-active-requests' },
  { key: 'activity.metric.queued_requests', en: 'Queued requests', ko: '대기 요청', test_id: 'activity-metric-queued-requests' },
  { key: 'activity.metric.completed_requests_total', en: 'Total completed requests', ko: '누적 완료 요청', test_id: 'activity-metric-completed-requests-total' },
  { key: 'activity.metric.completion_tokens_total', en: 'Total completion tokens', ko: '누적 완료 토큰', test_id: 'activity-metric-completion-tokens-total' },
  { key: 'activity.metric.gpu_utilization', en: 'GPU utilization', ko: 'GPU 사용률', test_id: 'activity-metric-gpu-utilization' },
  { key: 'activity.metric.ttft', en: 'Time to first token', ko: '첫 토큰 도달 시간', test_id: 'activity-metric-ttft' },
  { key: 'activity.metric.decode_rate', en: 'Decode rate', ko: '디코드 속도', test_id: 'activity-metric-decode-rate' },
  { key: 'activity.metric.process_resident_bytes', en: 'Process resident memory', ko: '프로세스 상주 메모리', test_id: 'activity-metric-process-resident-bytes' },
  { key: 'activity.metric.allocator_active_bytes', en: 'Active allocator memory', ko: '할당자 활성 메모리', test_id: 'activity-metric-allocator-active-bytes' },
  { key: 'activity.metric.allocator_cache_bytes', en: 'Cached allocator memory', ko: '할당자 캐시 메모리', test_id: 'activity-metric-allocator-cache-bytes' },
  { key: 'activity.metric.allocator_peak_bytes', en: 'Peak allocator memory', ko: '할당자 최대 메모리', test_id: 'activity-metric-allocator-peak-bytes' },
  { key: 'activity.metric.device_total_bytes', en: 'Device memory', ko: '장치 메모리', test_id: 'activity-metric-device-total-bytes' },
  { key: 'activity.metric.model_weights_bytes', en: 'Model weights estimate', ko: '모델 가중치 추정량', test_id: 'activity-metric-model-weights-bytes' },
  { key: 'activity.metric.kv_cache_bytes', en: 'KV cache memory', ko: 'KV 캐시 메모리', test_id: 'activity-metric-kv-cache-bytes' },
  { key: 'activity.metric.generation_time_ms_total', en: 'Total generation time', ko: '누적 생성 시간', test_id: 'activity-metric-generation-time-ms-total' },
  { key: 'activity.metric.decode_tokens_total', en: 'Accepted decode tokens', ko: '수락된 디코드 토큰', test_id: 'activity-metric-decode-tokens-total' },
  { key: 'activity.metric.decode_time_us_total', en: 'Total decode time', ko: '누적 디코드 시간', test_id: 'activity-metric-decode-time-us-total' },
  { key: 'activity.metric.prompt_cache_bytes', en: 'Prompt cache memory', ko: '프롬프트 캐시 메모리', test_id: 'activity-metric-prompt-cache-bytes' },
  { key: 'activity.metric.prompt_cache_entries', en: 'Prompt cache entries', ko: '프롬프트 캐시 항목', test_id: 'activity-metric-prompt-cache-entries' },
] as const;

/** Metric names that have a translated label; unknown names fall back to the raw metric identifier. */
export type ActivityMetricKey = Extract<typeof activityStrings[number]['key'], `activity.metric.${string}`>;
