// Copyright 2026 Lablup Inc. Licensed under the Apache License, Version 2.0.
// Activity copy. Metric labels are keyed as activity.metric.<metric_name>; every
// entry is mirrored in tests/fixtures/webui/strings.json.
export const activityStrings = [
  { key: 'activity.intro', en: 'Operations and runtime observations. Browsing never loads a model.', ko: '작업과 런타임 관측입니다. 조회는 모델을 로드하지 않습니다.', test_id: 'activity-intro' },
  { key: 'activity.session', en: 'History belongs to this server session: up to 200 terminal operations for one hour. A restart clears it; reconnect reconciles the authoritative snapshot.', ko: '기록은 서버 세션에 속합니다. 완료 작업 최대 200개를 한 시간 보관하며, 재시작 시 초기화하고 재연결 시 서버 상태와 대조합니다.', test_id: 'activity-session' },
  { key: 'activity.export', en: 'Export sanitized diagnostics', ko: '민감 정보 없는 진단 내보내기', test_id: 'activity-export' },
  { key: 'activity.refresh', en: 'Refresh observations', ko: '관측 새로고침', test_id: 'activity-refresh' },
  { key: 'activity.stale', en: 'Observations are stale. Last values are not current measurements.', ko: '관측이 최신 상태가 아닙니다. 마지막 값은 현재 측정값이 아닙니다.', test_id: 'activity-stale' },
  { key: 'activity.updated', en: 'Last snapshot {time}.', ko: '마지막 스냅샷 {time}.', test_id: 'activity-updated' },
  { key: 'activity.pending', en: 'Waiting for the first snapshot.', ko: '첫 스냅샷을 기다리는 중입니다.', test_id: 'activity-pending' },
  { key: 'activity.operations', en: 'Operations', ko: '작업', test_id: 'activity-operations' },
  { key: 'activity.operations.counts', en: '{active} active · {failed} failed', ko: '진행 중 {active}건 · 실패 {failed}건', test_id: 'activity-operations-counts' },
  { key: 'activity.operations.empty.title', en: 'No operations in this session', ko: '이 세션의 작업 없음', test_id: 'activity-operations-empty-title' },
  { key: 'activity.session_help', en: 'About operation history', ko: '작업 기록 안내', test_id: 'activity-session-help' },
  { key: 'activity.kind.catalog_refresh', en: 'Catalog refresh', ko: '카탈로그 새로고침', test_id: 'activity-kind-catalog-refresh' },
  { key: 'activity.kind.model_load', en: 'Model load', ko: '모델 로드', test_id: 'activity-kind-model-load' },
  { key: 'activity.kind.model_unload', en: 'Model unload', ko: '모델 언로드', test_id: 'activity-kind-model-unload' },
  { key: 'activity.kind.download', en: 'Download', ko: '다운로드', test_id: 'activity-kind-download' },
  { key: 'activity.kind.model_removal', en: 'Model removal', ko: '모델 삭제', test_id: 'activity-kind-model-removal' },
  { key: 'activity.kind.settings_patch', en: 'Settings change', ko: '설정 변경', test_id: 'activity-kind-settings-patch' },
  { key: 'activity.state.queued', en: 'Queued', ko: '대기 중', test_id: 'activity-state-queued' },
  { key: 'activity.state.running', en: 'Running', ko: '실행 중', test_id: 'activity-state-running' },
  { key: 'activity.state.cancelling', en: 'Cancelling', ko: '취소 중', test_id: 'activity-state-cancelling' },
  { key: 'activity.state.succeeded', en: 'Succeeded', ko: '완료', test_id: 'activity-state-succeeded' },
  { key: 'activity.state.failed', en: 'Failed', ko: '실패', test_id: 'activity-state-failed' },
  { key: 'activity.state.cancelled', en: 'Cancelled', ko: '취소됨', test_id: 'activity-state-cancelled' },
  { key: 'activity.target.unknown_model', en: 'Unknown model', ko: '알 수 없는 모델', test_id: 'activity-target-unknown-model' },
  { key: 'activity.cancel', en: 'Request cancellation', ko: '취소 요청', test_id: 'activity-cancel' },
  { key: 'activity.cancelling', en: 'Cancellation requested; waiting for worker acknowledgement.', ko: '취소 요청됨. 작업자 확인을 기다립니다.', test_id: 'activity-cancelling' },
  { key: 'activity.failure', en: 'The action failed. Check its state and refresh before retrying from Models.', ko: '작업에 실패했습니다. 상태를 확인하고 새로고침한 후 모델 화면에서 재시도하세요.', test_id: 'activity-failure' },
  { key: 'activity.failure_no_code', en: 'The server did not report an error code.', ko: '서버가 오류 코드를 보고하지 않았습니다.', test_id: 'activity-failure-no-code' },
  { key: 'activity.error.invalid_request', en: 'The request was not valid.', ko: '요청이 올바르지 않습니다.', test_id: 'activity-error-invalid-request' },
  { key: 'activity.error.unauthorized', en: 'The server did not accept the credentials.', ko: '서버가 인증 정보를 받아들이지 않았습니다.', test_id: 'activity-error-unauthorized' },
  { key: 'activity.error.forbidden', en: 'This server does not allow this action.', ko: '이 서버에서는 허용되지 않는 작업입니다.', test_id: 'activity-error-forbidden' },
  { key: 'activity.error.not_found', en: 'The target no longer exists.', ko: '대상이 더 이상 존재하지 않습니다.', test_id: 'activity-error-not-found' },
  { key: 'activity.error.stale_revision', en: 'The model changed before the action ran.', ko: '작업이 실행되기 전에 모델이 변경되었습니다.', test_id: 'activity-error-stale-revision' },
  { key: 'activity.error.conflict', en: 'Another operation conflicted with this one.', ko: '다른 작업과 충돌했습니다.', test_id: 'activity-error-conflict' },
  { key: 'activity.error.unsupported', en: 'This action is not supported for this target.', ko: '이 대상에서는 지원하지 않는 작업입니다.', test_id: 'activity-error-unsupported' },
  { key: 'activity.error.rate_limited', en: 'Too many requests. Try again later.', ko: '요청이 너무 많습니다. 잠시 후 다시 시도하세요.', test_id: 'activity-error-rate-limited' },
  { key: 'activity.error.unavailable', en: 'A required resource was unavailable.', ko: '필요한 리소스를 사용할 수 없었습니다.', test_id: 'activity-error-unavailable' },
  { key: 'activity.error.payload_too_large', en: 'The request was too large.', ko: '요청이 너무 큽니다.', test_id: 'activity-error-payload-too-large' },
  { key: 'activity.error.server_restarted', en: 'The server restarted during the action.', ko: '작업 중에 서버가 다시 시작되었습니다.', test_id: 'activity-error-server-restarted' },
  { key: 'activity.error.event_gap', en: 'Progress updates were lost. Refresh to reconcile the operation.', ko: '진행 상황 업데이트가 누락되었습니다. 새로고침하여 작업 상태를 대조하세요.', test_id: 'activity-error-event-gap' },
  { key: 'activity.error.partial_success', en: 'The action only partly succeeded.', ko: '작업이 일부만 성공했습니다.', test_id: 'activity-error-partial-success' },
  { key: 'activity.error.other', en: 'The server reported an error this page does not recognize.', ko: '이 화면이 인식하지 못하는 오류를 서버가 보고했습니다.', test_id: 'activity-error-other' },
  { key: 'activity.details.error_code', en: 'Error code: {code}', ko: '오류 코드: {code}', test_id: 'activity-details-error-code' },
  { key: 'activity.cancel_failed', en: 'Cancellation could not be confirmed. Refresh to reconcile the operation.', ko: '취소를 확인하지 못했습니다. 새로고침하여 작업 상태를 대조하세요.', test_id: 'activity-cancel-failed' },
  { key: 'activity.cancel_unsupported', en: 'Cannot be cancelled', ko: '취소할 수 없음', test_id: 'activity-cancel-unsupported' },
  { key: 'activity.bytes', en: 'Download progress', ko: '다운로드 진행률', test_id: 'activity-bytes' },
  { key: 'activity.download_progress', en: '{completed} / {total}', ko: '{completed} / {total}', test_id: 'activity-download-progress' },
  { key: 'activity.details', en: 'Operation details', ko: '작업 상세', test_id: 'activity-details' },
  { key: 'activity.details.operation_id', en: 'Operation ID: {id}', ko: '작업 ID: {id}', test_id: 'activity-details-operation-id' },
  { key: 'activity.details.model_id', en: 'Model ID: {id}', ko: '모델 ID: {id}', test_id: 'activity-details-model-id' },
  { key: 'activity.details.updated', en: 'Updated {time}', ko: '{time} 갱신', test_id: 'activity-details-updated' },
  { key: 'activity.runtime', en: 'Selected model runtime', ko: '선택한 모델 런타임', test_id: 'activity-runtime' },
  { key: 'activity.model', en: 'Observed model', ko: '관측 모델', test_id: 'activity-model' },
  { key: 'activity.select', en: 'Select a model to observe', ko: '관측할 모델 선택', test_id: 'activity-select' },
  { key: 'activity.select_body', en: 'Use the model picker. Selection does not load the model.', ko: '모델 선택기를 사용하세요. 선택만으로 모델을 로드하지 않습니다.', test_id: 'activity-select-body' },
  { key: 'activity.unavailable', en: 'No runtime sample has been received for this model.', ko: '이 모델의 런타임 샘플을 아직 받지 못했습니다.', test_id: 'activity-unavailable' },
  { key: 'activity.waiting', en: 'Waiting for the first runtime sample', ko: '첫 런타임 샘플을 기다리는 중', test_id: 'activity-waiting' },
  { key: 'activity.runtime_stale', en: 'The runtime snapshot has stopped refreshing; the values below are the last observation.', ko: '런타임 스냅샷이 갱신되지 않고 있습니다. 아래 값은 마지막 관측값입니다.', test_id: 'activity-runtime-stale' },
  { key: 'activity.observed_at', en: 'Observed at {time}', ko: '{time} 관측', test_id: 'activity-observed-at' },
  { key: 'activity.unknown_time', en: 'No observation time', ko: '관측 시각 없음', test_id: 'activity-unknown-time' },
  { key: 'activity.reason.metrics_disabled', en: 'Metrics are off. Restart the server with --metrics.', ko: '메트릭이 꺼져 있습니다. --metrics로 서버를 다시 시작하세요.', test_id: 'activity-reason-metrics-disabled' },
  { key: 'activity.reason.not_loaded', en: 'The model is not loaded, so there are no live counters.', ko: '모델이 로드되지 않아 실시간 카운터가 없습니다.', test_id: 'activity-reason-not-loaded' },
  { key: 'activity.reason.single_stream', en: 'This single-stream model does not publish this counter.', ko: '단일 스트림 모델은 이 카운터를 제공하지 않습니다.', test_id: 'activity-reason-single-stream' },
  { key: 'activity.reason.counter_unavailable', en: 'The server did not report this counter.', ko: '서버가 이 카운터를 보고하지 않았습니다.', test_id: 'activity-reason-counter-unavailable' },
  { key: 'activity.reason.see_details', en: 'See All measurements and sources for the reason.', ko: '사유는 전체 측정값과 출처에서 확인하세요.', test_id: 'activity-reason-see-details' },
  { key: 'activity.metric_details', en: 'All measurements and sources', ko: '전체 측정값과 출처', test_id: 'activity-metric-details' },
  { key: 'activity.unavailable_badge', en: '{count} unavailable', ko: '{count}개 사용 불가', test_id: 'activity-unavailable-badge' },
  { key: 'activity.memory', en: 'Memory figures have separate scopes and may overlap. Do not add process, allocator, device and cache values together.', ko: '메모리 수치는 서로 다른 범위이며 중복될 수 있습니다. 프로세스, 할당자, 장치 및 캐시 값을 합산하지 마세요.', test_id: 'activity-memory' },
  { key: 'activity.timing', en: 'Server counters are not browser TTFT. Chat shows request-send to first reasoning/content delta separately; no rendered word counts are used as tokens.', ko: '서버 카운터는 브라우저 TTFT가 아닙니다. 채팅은 요청 전송부터 첫 추론/내용 델타까지 별도로 표시하며, 단어 수를 토큰으로 사용하지 않습니다.', test_id: 'activity-timing' },
  { key: 'activity.scope', en: 'Scope: {scope}', ko: '범위: {scope}', test_id: 'activity-scope' },
  { key: 'activity.scope.model', en: 'Model', ko: '모델', test_id: 'activity-scope-model' },
  { key: 'activity.scope.slot', en: 'Slot', ko: '슬롯', test_id: 'activity-scope-slot' },
  { key: 'activity.scope.pool', en: 'Shared pool', ko: '공유 풀', test_id: 'activity-scope-pool' },
  { key: 'activity.scope.server', en: 'Server', ko: '서버', test_id: 'activity-scope-server' },
  { key: 'activity.scope.unknown', en: 'Unknown', ko: '알 수 없음', test_id: 'activity-scope-unknown' },
  { key: 'activity.history.note', en: 'Five-minute in-memory history, at most 150 two-second samples. Hidden tabs stop observation; gaps and counter resets are not interpolated.', ko: '메모리 내 5분 기록이며 2초 간격 최대 150개입니다. 숨겨진 탭은 관측을 중지합니다. 공백과 카운터 초기화를 보간하지 않습니다.', test_id: 'activity-history-note' },
  { key: 'activity.history.empty', en: 'No active request samples in the last five minutes.', ko: '최근 5분 동안 활성 요청 샘플이 없습니다.', test_id: 'activity-history-empty' },
  { key: 'activity.chart.label', en: 'Active requests: discrete observations over the last five minutes', ko: '활성 요청: 최근 5분 동안의 개별 관측값', test_id: 'activity-chart-label' },
  { key: 'activity.chart.title', en: 'Active requests (requests, selected model)', ko: '활성 요청 (요청 수, 선택한 모델)', test_id: 'activity-chart-title' },
  { key: 'activity.chart.point', en: '{value} requests', ko: '요청 {value}건', test_id: 'activity-chart-point' },
  { key: 'activity.chart.point_one', en: '{value} request', ko: '요청 {value}건', test_id: 'activity-chart-point-one' },
  { key: 'activity.slots', en: 'Request slots', ko: '요청 슬롯', test_id: 'activity-slots' },
  { key: 'activity.slot', en: 'Slot', ko: '슬롯', test_id: 'activity-slot' },
  { key: 'activity.slot_state', en: 'State', ko: '상태', test_id: 'activity-slot-state' },
  { key: 'activity.occupancy', en: 'Context occupancy', ko: '컨텍스트 점유', test_id: 'activity-occupancy' },
  { key: 'activity.decoded', en: 'Decoded tokens', ko: '디코드 토큰', test_id: 'activity-decoded' },
  { key: 'activity.cached', en: 'Cached prompt tokens', ko: '캐시된 프롬프트 토큰', test_id: 'activity-cached' },
  { key: 'activity.processing', en: 'Processing', ko: '처리 중', test_id: 'activity-processing' },
  { key: 'activity.idle', en: 'Idle', ko: '유휴', test_id: 'activity-idle' },
  { key: 'activity.context', en: 'Request context window: {tokens}', ko: '요청 컨텍스트 한도: {tokens}', test_id: 'activity-context' },
  { key: 'activity.pool', en: 'Shared pool context: {tokens}', ko: '공유 풀 컨텍스트: {tokens}', test_id: 'activity-pool' },
  { key: 'activity.parallel', en: 'Effective parallelism: {effective} / {configured}', ko: '실제 병렬도: {effective} / {configured}', test_id: 'activity-parallel' },
  { key: 'activity.no_context', en: 'unknown (no context limit reported)', ko: '알 수 없음 (컨텍스트 한도 미보고)', test_id: 'activity-no-context' },
  { key: 'activity.slot_progress', en: '{used} / {total} tokens', ko: '{used} / {total} 토큰', test_id: 'activity-slot-progress' },
  { key: 'activity.slot_occupancy', en: 'Slot {id} context occupancy', ko: '슬롯 {id} 컨텍스트 점유율', test_id: 'activity-slot-occupancy' },
  { key: 'activity.slots_empty', en: 'The server reported no slots.', ko: '서버가 보고한 슬롯이 없습니다.', test_id: 'activity-slots-empty' },
  { key: 'activity.slots_reason.disabled', en: 'Slots are off. Restart the server with --slots.', ko: '슬롯 관측이 꺼져 있습니다. --slots로 서버를 다시 시작하세요.', test_id: 'activity-slots-reason-disabled' },
  { key: 'activity.slots_reason.not_loaded', en: 'The model is not loaded, so no slots are observed.', ko: '모델이 로드되지 않아 슬롯을 관측할 수 없습니다.', test_id: 'activity-slots-reason-not-loaded' },
  { key: 'activity.slots_reason.registry', en: 'The slot registry is unavailable.', ko: '슬롯 레지스트리를 사용할 수 없습니다.', test_id: 'activity-slots-reason-registry' },
  { key: 'activity.slots_reason.partial', en: 'Partial list: showing the first 256 observational slots.', ko: '일부 목록: 처음 256개 관측 슬롯만 표시합니다.', test_id: 'activity-slots-reason-partial' },
  { key: 'activity.slots_reason.unavailable', en: 'Slots are unavailable.', ko: '슬롯을 관측할 수 없습니다.', test_id: 'activity-slots-reason-unavailable' },
  { key: 'activity.slots_reason.other', en: 'The server reported a slot condition this page does not recognize.', ko: '이 화면이 인식하지 못하는 슬롯 상태를 서버가 보고했습니다.', test_id: 'activity-slots-reason-other' },
  { key: 'activity.slots_reason.raw', en: 'Server reason', ko: '서버 사유', test_id: 'activity-slots-reason-raw' },
  { key: 'activity.unit.requests', en: '{value} requests', ko: '{value}건', test_id: 'activity-unit-requests' },
  { key: 'activity.unit.request_one', en: '{value} request', ko: '{value}건', test_id: 'activity-unit-request-one' },
  { key: 'activity.unit.tokens', en: '{value} tokens', ko: '{value} 토큰', test_id: 'activity-unit-tokens' },
  { key: 'activity.unit.token_one', en: '{value} token', ko: '{value} 토큰', test_id: 'activity-unit-token-one' },
  { key: 'activity.unit.ms', en: '{value} ms', ko: '{value}ms', test_id: 'activity-unit-ms' },
  { key: 'activity.unit.us', en: '{value} µs', ko: '{value}µs', test_id: 'activity-unit-us' },
  { key: 'activity.unit.percent', en: '{value}%', ko: '{value}%', test_id: 'activity-unit-percent' },
  { key: 'activity.unit.entries', en: '{value} entries', ko: '항목 {value}개', test_id: 'activity-unit-entries' },
  { key: 'activity.unit.entry_one', en: '{value} entry', ko: '항목 {value}개', test_id: 'activity-unit-entry-one' },
  { key: 'activity.unit.tokens_per_second', en: '{value} tokens/s', ko: '초당 {value} 토큰', test_id: 'activity-unit-tokens-per-second' },
  { key: 'activity.metric.active_requests', en: 'Active requests', ko: '활성 요청', test_id: 'activity-metric-active-requests' },
  { key: 'activity.metric.queued_requests', en: 'Queued requests', ko: '대기 요청', test_id: 'activity-metric-queued-requests' },
  { key: 'activity.metric.completed_requests_total', en: 'Total completed requests', ko: '누적 완료 요청', test_id: 'activity-metric-completed-requests-total' },
  { key: 'activity.metric.completion_tokens_total', en: 'Total completion tokens', ko: '누적 완료 토큰', test_id: 'activity-metric-completion-tokens-total' },
  { key: 'activity.metric.gpu_utilization', en: 'GPU utilization', ko: 'GPU 사용률', test_id: 'activity-metric-gpu-utilization' },
  { key: 'activity.metric.ttft', en: 'Time to first token', ko: '첫 토큰 도달 시간', test_id: 'activity-metric-ttft' },
  { key: 'activity.metric.decode_rate', en: 'Decode rate', ko: '디코드 속도', test_id: 'activity-metric-decode-rate' },
  { key: 'activity.metric.process_resident_bytes', en: 'Process resident memory', ko: '프로세스 상주 메모리', test_id: 'activity-metric-process-resident-bytes' },
  { key: 'activity.metric.allocator_active_bytes', en: 'Active allocator memory', ko: '할당자 활성 메모리', test_id: 'activity-metric-allocator-active-bytes' },
  { key: 'activity.metric.allocator_cache_bytes', en: 'Cached allocator memory', ko: '할당자 캐시 메모리', test_id: 'activity-metric-allocator-cache-bytes' },
  { key: 'activity.metric.allocator_peak_bytes', en: 'Peak allocator memory', ko: '할당자 최대 메모리', test_id: 'activity-metric-allocator-peak-bytes' },
  { key: 'activity.metric.device_total_bytes', en: 'Device memory', ko: '장치 메모리', test_id: 'activity-metric-device-total-bytes' },
  { key: 'activity.metric.model_weights_bytes', en: 'Model weights estimate', ko: '모델 가중치 추정량', test_id: 'activity-metric-model-weights-bytes' },
  { key: 'activity.metric.kv_cache_bytes', en: 'KV cache memory', ko: 'KV 캐시 메모리', test_id: 'activity-metric-kv-cache-bytes' },
  { key: 'activity.metric.generation_time_ms_total', en: 'Total generation time', ko: '누적 생성 시간', test_id: 'activity-metric-generation-time-ms-total' },
  { key: 'activity.metric.decode_tokens_total', en: 'Accepted decode tokens', ko: '수락된 디코드 토큰', test_id: 'activity-metric-decode-tokens-total' },
  { key: 'activity.metric.decode_time_us_total', en: 'Total decode time', ko: '누적 디코드 시간', test_id: 'activity-metric-decode-time-us-total' },
  { key: 'activity.metric.prompt_cache_bytes', en: 'Prompt cache memory', ko: '프롬프트 캐시 메모리', test_id: 'activity-metric-prompt-cache-bytes' },
  { key: 'activity.metric.prompt_cache_entries', en: 'Prompt cache entries', ko: '프롬프트 캐시 항목', test_id: 'activity-metric-prompt-cache-entries' },
] as const;

/** Metric names that have a translated label; unknown names fall back to the raw metric identifier. */
export type ActivityMetricKey = Extract<typeof activityStrings[number]['key'], `activity.metric.${string}`>;
