// Copyright 2025-2026 Lablup Inc. and Jeongkyu Shin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Core batch scheduler with iteration-level scheduling and chunked prefill.
//!
//! [`BatchScheduler`] replaces the sequential `loop { request_rx.recv() }`
//! pattern in the model worker. At each tick it decides whether to:
//!
//! - **Prefill** (or continue a chunked prefill of) a queued request,
//! - **Decode** one token for each active sequence, or
//! - **Idle** (block until the next request arrives).
//!
//! When `prefill_chunk_size > 0`, long prompts are broken into chunks and
//! decode steps are interleaved between chunks so active sequences are not
//! starved during prefill of large prompts.

use std::collections::HashSet;
use std::rc::Rc;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc;
use std::time::Instant;

use mlxcel_core::cache::{
    BatchKvQuantConfig, CachePool, DetachedPagedCacheSet, KVCacheMode, PagedKvLayout, SequenceId,
    SequenceStateBackend, SequenceStateLayout,
};
use mlxcel_core::generate::{
    DecodeBatchContext, DecodeStorageBackend as CoreDecodeStorageBackend, LanguageModel,
};
use mlxcel_core::generation_policy::{
    initial_token_history, merged_eos_token_ids, seed_rng_if_needed,
};
use mlxcel_core::hardware;
use mlxcel_core::sampling::{
    FusedSampleParams, LogprobSource, TokenBiasMap, apply_row_filters, batched_fused_sample,
    compute_logprobs, compute_post_sampling_probs, row_supports_fused_batch,
    sample_token_optimized, sample_token_optimized_with_state,
    sample_token_with_state_and_distribution,
};
use mlxcel_core::streams::{
    install_thread_local_default_stream, new_thread_local_generation_stream,
};
use mlxcel_core::utils::{align_to_na_tile, create_padded_prefill_mask};
use mlxcel_core::{MlxThreadLocalStream, UniquePtr};

use crate::LoadedModel;
use crate::models::gemma4_mtp_target::{
    Gemma4MtpTargetAdapter, Gemma4UnifiedMtpTargetAdapter, Gemma4VLMtpTargetAdapter,
};
use crate::server::ServerGenerateOptions;
use crate::server::batch::observability::{BatchObservability, apc_trace_enabled};
use crate::server::config::{
    DecodeStorageBackend, PreemptionPolicy, PromptCacheRequestContext, ReasoningBudgetOverride,
};
use crate::server::model_provider::model_worker::{
    StreamingDecodeState, build_generation_result_with_cache, merge_config_stop_tokens,
    prepare_request_vlm_embeddings,
};
use crate::server::model_provider::{GenerateEvent, ModelRequest};
use crate::server::prompt_cache::key::PromptCacheKey;
use crate::server::prompt_cache::metrics::PromptCacheRejectReason;
use crate::server::prompt_cache::{
    CacheEntry, DetachedKvSet, ModelSnapshotEntry, PromptCacheStore, SnapshotLookupOutcome,
    SnapshotOrigin,
};
use crate::server::state::BatchMetrics;
use crate::server::thinking_budget::{
    ThinkingBudget, ThinkingDecision, ThinkingState, ThinkingTokenIds, resolve_request_budget,
};
use crate::tokenizer::MlxcelTokenizer;
use crate::vision::feature_cache::ModelVisionCaches;
use crate::vlm_runtime::prepared_embedding_refs;

use super::active::ActiveBatch;
use super::prefill_cohort::{
    PrefillCohortKind, PrefillRow, batched_window_admits, batched_window_admits_lora,
    default_batched_prefill_token_budget, plan_prefill_cohorts,
};
use super::queue::PrefillQueue;
use super::sequence::{
    BatchSchedulerAction, ContextRetentionPolicy, FinishReason, RequestPriority, SequenceInfo,
    SequenceRetention, SequenceState,
};
use super::stop_matcher::StopMatcher;
use super::tick_policy::{
    TickChoice, TickState, decide_tick, mixed_step_enabled, resolve_prefill_grant_interval,
};

/// Returns true when the current hardware is M5+ with Neural Accelerator
/// support and tile-aligned prefill should be applied.
#[inline]
fn should_align_prefill() -> bool {
    let hw = hardware::get_hardware();
    hw.has_neural_accelerator && hw.macos_supports_na
}

pub(crate) const DEFAULT_PAGED_BLOCK_SIZE: usize = 32;

/// Rebuild the per-request thinking tracker on either side of a handoff.
///
/// The decode side replays tokens already generated by prefill so the next
/// sampled token observes the same block phase and budget count as a
/// single-node sequence.
fn build_handoff_thinking_state(
    token_ids: Option<ThinkingTokenIds>,
    reasoning_budget: i32,
    max_tokens: usize,
    enter_block_on_start: bool,
    generated_tokens: &[i32],
) -> anyhow::Result<ThinkingState> {
    let budget = resolve_request_budget(Some(reasoning_budget), None, max_tokens)?;
    let mut state = match token_ids {
        Some(ids) => ThinkingState::new(Some(ids), budget, enter_block_on_start),
        None => ThinkingState::disabled(),
    };
    for &token in generated_tokens {
        state.observe(token);
    }
    Ok(state)
}

/// Environment override for the #715 batched-prefill token budget.
const MAX_BATCH_PREFILL_TOKENS_ENV: &str = "MLXCEL_MAX_BATCH_PREFILL_TOKENS";

/// #822: consecutive MLX eval failures at the decode/prefill FFI boundary that
/// the scheduler tolerates before treating the backend as unrecoverable and
/// shutting down cleanly. The decode loop evaluates on-device tensors through
/// the fallible `try_eval` / `try_async_eval` boundary so a single MLX C++
/// throw (a graph-cache abort at capture, an allocation failure, ...) fails the
/// affected request(s) instead of aborting the whole process. A graph-capture
/// throw is clean to fail per-batch, but an OOM or internal-invariant throw may
/// leave the allocator/device in an undefined state; once failures hit this
/// bound the scheduler stops rather than spinning on a broken backend. The goal
/// is graceful request-scoped failure OR clean shutdown, NOT pretend-recovery.
const MAX_CONSECUTIVE_EVAL_FAILURES: u32 = 8;

/// #822: advance the consecutive decode-eval failure counter for one eval
/// outcome. A successful eval (`eval_ok == true`) resets the run to 0; a failure
/// bumps it, saturating so an extreme failure streak cannot wrap. Pure so the
/// guard's arithmetic is unit-testable without a live model.
fn advance_eval_failure_count(current: u32, eval_ok: bool) -> u32 {
    if eval_ok {
        0
    } else {
        current.saturating_add(1)
    }
}

/// #822: whether the consecutive decode-eval failure count has reached the
/// unrecoverable-backend threshold ([`MAX_CONSECUTIVE_EVAL_FAILURES`]) at which
/// the scheduler drains in-flight requests and shuts down instead of spinning.
fn eval_failures_reached_limit(count: u32) -> bool {
    count >= MAX_CONSECUTIVE_EVAL_FAILURES
}

/// Resolve the effective batched-prefill padded-token budget (#715).
///
/// Precedence (matching the `--flag` > env convention of the other server
/// knobs): the explicit CLI/config value (`configured`, `Some` only when the
/// flag was passed) wins; otherwise the `MLXCEL_MAX_BATCH_PREFILL_TOKENS` env
/// var if set to a valid integer; otherwise the derived default
/// [`default_batched_prefill_token_budget`]. A resolved value of `0` disables
/// the cap (uncapped escape hatch) at every level.
fn resolve_max_batch_prefill_tokens(
    configured: Option<usize>,
    prefill_chunk_size: usize,
    max_batch_prefill: usize,
) -> usize {
    if let Some(value) = configured {
        return value;
    }
    if let Ok(raw) = std::env::var(MAX_BATCH_PREFILL_TOKENS_ENV)
        && let Ok(parsed) = raw.trim().parse::<usize>()
    {
        return parsed;
    }
    default_batched_prefill_token_budget(prefill_chunk_size, max_batch_prefill)
}

/// Decide whether a request may participate in experimental VLM prompt-prefix
/// cache sharing (#124 step c).
///
/// Sharing is allowed only when all three hold:
/// 1. the operator opted in (`--enable-vlm-prefix-cache`),
/// 2. the request actually carries multimodal content, and
/// 3. it has no video payload (video frame bytes are NOT folded into the
///    request's multimodal digest, so a video prefix could collide with a
///    different video in the same bucket).
///
/// Text-only requests and any request with video always return `false`,
/// preserving the legacy cold-prefill path. Keeping the decision in one pure
/// function lets the safety conditions be pinned by a unit test so a future
/// edit cannot silently enable-by-default or allow video sharing.
#[inline]
fn vlm_prefix_sharing_allowed(
    enabled: bool,
    is_multimodal: bool,
    has_videos: bool,
    requires_mode_restore: bool,
) -> bool {
    enabled && is_multimodal && !has_videos && !requires_mode_restore
}

fn effective_decode_storage_backend(
    requested: DecodeStorageBackend,
    max_batch_size: usize,
    supports_batching: bool,
    supports_paged_decode_backend: bool,
) -> DecodeStorageBackend {
    let paged_available = max_batch_size > 1 && supports_batching && supports_paged_decode_backend;
    match requested {
        DecodeStorageBackend::Auto | DecodeStorageBackend::Paged if paged_available => {
            DecodeStorageBackend::Paged
        }
        DecodeStorageBackend::Auto | DecodeStorageBackend::Paged => DecodeStorageBackend::Dense,
        DecodeStorageBackend::Dense => DecodeStorageBackend::Dense,
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct ChunkedPrefillRange {
    start: usize,
    end: usize,
    is_terminal: bool,
}

/// Length of the longest common prefix of two token vectors.
///
/// Used by: `BatchScheduler::resolve_history_boundary` (issue #1143)
#[inline]
fn common_prefix_len(a: &[i32], b: &[i32]) -> usize {
    a.iter().zip(b).take_while(|(x, y)| x == y).count()
}

/// Decide the history boundary for a request from its two token vectors.
///
/// Split out from [`BatchScheduler::resolve_history_boundary`] so the
/// arithmetic that decides whether a boundary snapshot is worth taking is a
/// pure function with its own tests (issue #1143). Returns the clipped
/// boundary length, or `None` when this request should not carry one.
///
/// `history` is the tokenized `add_generation_prompt = false` render and
/// `prompt_tokens` is what the model will actually prefill. The result is the
/// length of their longest common prefix, subject to two rejections:
///
/// * below `min_prefix_tokens` the store would decline the insert anyway, so
///   the extra forward would be pure loss;
/// * at or beyond the prompt length there is no suffix left to prefill, and
///   the sampler needs a non-empty final forward to produce fresh logits.
///
/// Used by: `BatchScheduler::resolve_history_boundary`
fn history_boundary_len(
    history: &[i32],
    prompt_tokens: &[i32],
    min_prefix_tokens: usize,
) -> Option<usize> {
    let boundary = common_prefix_len(history, prompt_tokens);
    if boundary < min_prefix_tokens || boundary >= prompt_tokens.len() {
        return None;
    }
    Some(boundary)
}

/// Whether a resolved boundary is still worth capturing for this sequence at
/// prefill time (issue #1143).
///
/// Separate from [`history_boundary_len`] because it depends on state that only
/// exists once the sequence has been admitted: an adopted prompt-cache prefix
/// may already reach past the boundary, in which case the segment forward would
/// be empty and the snapshot already exists.
///
/// Used by: `BatchScheduler::capture_history_boundary_snapshot`
#[inline]
fn boundary_capture_applies(
    boundary: usize,
    prefill_start_offset: usize,
    prompt_len: usize,
) -> bool {
    boundary > prefill_start_offset && boundary < prompt_len
}

#[inline]
fn next_chunked_prefill_range(
    prompt_len: usize,
    offset: usize,
    chunk_size: usize,
) -> Option<ChunkedPrefillRange> {
    if chunk_size == 0 || offset >= prompt_len {
        return None;
    }
    let end = offset.saturating_add(chunk_size).min(prompt_len);
    Some(ChunkedPrefillRange {
        start: offset,
        end,
        is_terminal: end >= prompt_len,
    })
}

/// Core batch scheduler that drives the model worker loop.
///
/// Replaces the old sequential `recv()` loop with an iteration-level scheduler
/// that interleaves prefill and decode operations. When `max_batch_size == 1`
/// (the default), behavior is identical to the pre-scheduler worker loop.
///
/// When `prefill_chunk_size > 0`, long prompts are processed in chunks with
/// decode interleaving to prevent latency spikes for active sequences.
pub struct BatchScheduler {
    // -- Pool & scheduling structures --
    cache_pool: CachePool,
    prefill_queue: PrefillQueue,
    active_batch: ActiveBatch,

    // -- Model & tokenizer --
    model: LoadedModel,
    tokenizer: MlxcelTokenizer,
    /// Memo for the tokenized `--reasoning-budget-message` (#1470), keyed by
    /// the message text so a changed live setting re-encodes. One entry is
    /// enough: the message is a server-wide setting delivered per request.
    forced_reasoning_message: std::cell::RefCell<Option<(String, std::sync::Arc<Vec<i32>>)>>,

    // -- Runtime LoRA (#1439) --
    /// The server's runtime-LoRA state, when adapters serve unfused. The
    /// scheduler applies each executing group's snapshot to the shared
    /// handles before its forwards, mirroring b10621's once-per-batch
    /// `common_set_adapter_lora`.
    pub(crate) lora_runtime: Option<Arc<crate::lora::RuntimeLoraSet>>,
    /// The snapshot currently written into the handles, so repeated ticks of
    /// one batch write nothing.
    pub(crate) lora_applied: Option<Arc<Vec<f32>>>,

    // -- Generation infrastructure --
    //
    // Thread-local generation stream owned by this scheduler. The TLS
    // handle resolves to a per-thread `MlxStream` on demand, which
    // keeps dispatch and synchronization paired on the same thread even
    // if construction and execution happen on different threads.
    // Currently constructed and run on the same thread; the TLS design
    // leaves room to separate them in the future if needed.
    // See `mlxcel_core::streams` and.
    generation_stream: Option<UniquePtr<MlxThreadLocalStream>>,

    // -- Request channel --
    request_rx: mpsc::Receiver<ModelRequest>,

    // -- Metrics --
    /// Shared metrics updated atomically for HTTP handlers to read.
    batch_metrics: Arc<BatchMetrics>,
    /// Detailed observability counters (prefill, decode, cache).
    batch_observability: Arc<BatchObservability>,

    // -- Configuration --
    config_eos: Vec<i32>,
    /// Number of prompt tokens per prefill chunk. 0 = chunking disabled.
    prefill_chunk_size: usize,
    /// Whether preemptive eviction is enabled.
    enable_preemption: bool,
    /// Policy for selecting the eviction victim.
    preemption_policy: PreemptionPolicy,

    // -- Chunked prefill in-progress state --
    /// Sequence currently undergoing chunked prefill. `None` when no chunked
    /// prefill is in progress.
    chunked_prefill_seq: Option<SequenceInfo>,

    /// Issue #908 prototype gate, read once from `MLXCEL_MIXED_STEP` at
    /// construction so the tick loop never touches the environment. False (the
    /// default) makes [`BatchSchedulerAction::MixedStep`] unreachable and keeps
    /// tick arbitration identical to the pre-#908 scheduler.
    mixed_step_enabled: bool,

    /// Issue #1011 fairness policy: how many consecutive contended decode ticks
    /// a parked chunked prefill yields before it is granted one
    /// (`--prefill-grant-interval` / `MLXCEL_PREFILL_GRANT_INTERVAL`). Resolved
    /// once at construction so the tick loop never touches the environment.
    /// `0` disables the grant and restores the pre-#1011 starvation.
    prefill_grant_interval: u32,

    /// Issue #1011 fairness ledger: consecutive contended ticks that resolved
    /// to `Decode` since the parked chunked prefill last ran a chunk.
    ///
    /// [`Self::decide_action`] is the ONLY writer, and it can only write the
    /// value the policy returned alongside the choice
    /// ([`super::tick_policy::TickDecision`]), so this field cannot drift out of
    /// step with the arbitration it feeds. Nothing else in the scheduler needs
    /// to remember to reset it.
    decode_ticks_since_prefill_grant: u32,

    // -- Shutdown flag --
    shutdown_requested: bool,

    /// #822: consecutive MLX eval failures at the decode/prefill FFI boundary.
    /// Bumped whenever a `try_eval` / `try_async_eval` catches an MLX C++ throw
    /// and reset to 0 on any successful eval. When it reaches
    /// [`MAX_CONSECUTIVE_EVAL_FAILURES`] the scheduler drains in-flight requests
    /// with an error and shuts down cleanly instead of spinning on a broken
    /// allocator/device.
    consecutive_decode_eval_failures: u32,

    // -- Batched prefill config --
    /// Maximum number of pending requests to batch together for prefill.
    /// When `> 1`, the scheduler may collect multiple queued requests and
    /// run a single batched forward pass. Falls back to sequential prefill
    /// when only one request is pending or on any error.
    max_batch_prefill: usize,
    /// #715: padded-token budget bounding a single batched-prefill window.
    ///
    /// The padded batched path pads every row of a cohort to the window's
    /// longest prompt `L` and materializes a stacked `[B, L, L]` FP32 attention
    /// mask, an `O(B*L^2)` transient. This caps `B*L` (`rows * max_len`) so the
    /// mask stays within `budget^2 / 2` elements; rows past the budget spill to
    /// the next tick and prefill via the chunked single-sequence path. `0`
    /// disables the cap (uncapped). Resolved once in [`Self::with_config`] /
    /// [`Self::with_max_batch_prefill_tokens`] from the env override, the CLI
    /// value, or the derived default (`2 * max_batch_prefill * prefill_chunk_size`).
    max_batch_prefill_tokens: usize,
    /// Decode-time sequence-state backend used by this scheduler.
    decode_storage_backend: DecodeStorageBackend,

    /// Server-wide KV cache quantization mode.
    ///
    /// When non-Fp16 the scheduler upgrades each newly-allocated sequence's
    /// per-layer `KVCache` to the configured mode (with Boundary-V policy
    /// applied for Turbo4 modes) immediately after `model.make_caches()`
    /// returns its default Fp16 caches. For paged decode this also picks
    /// the Turbo4-aware [`PagedKvLayout`] constructor so the per-page sidecar
    /// budget is reserved.
    ///
    /// Defaults to [`KVCacheMode::Fp16`] (bit-exact baseline).
    kv_cache_mode: KVCacheMode,

    /// server-wide batch KV quantization configuration.
    ///
    /// When [`BatchKvQuantConfig::is_enabled`] returns `true`, the
    /// scheduler resolves per-layer modes from this config (with the
    /// last layer optionally forced to FP16 per
    /// [`BatchKvQuantConfig::skip_last_layer`]) and uses them in place of
    /// the legacy [`Self::kv_cache_mode`]-driven path. When disabled
    /// (the default), the legacy path is bit-exact preserved.
    batch_kv_quant: BatchKvQuantConfig,

    /// maximum KV cache size for plain (non-sliding) `KVCache`
    /// instances managed by this scheduler's `CachePool`.
    ///
    /// When `Some(N)`, the scheduler enforces a hard cap on the **live KV
    /// window** of each per-layer plain `KVCache`: after every prefill
    /// chunk (full prefill, chunked prefill start, chunked prefill
    /// continuation) and every decode step,
    /// [`KVCache::trim_front_keep_sink`] is invoked on each cache whose
    /// `live_len()` exceeds `N`, pinning the sequence's resolved retained
    /// prefix (b10621 `--keep` / `n_keep`, #1472; a fixed 4-token attention
    /// sink before that, issue #718) and dropping tokens past it rather than
    /// the oldest tokens overall. Since #1472 the trim runs only under
    /// `--context-shift`; the default enforces the bound by refusing or
    /// stopping instead. **Crucially,
    /// the cache's monotonic `offset` is never decremented**,
    /// `trim_front_keep_sink` advances `live_start` so RoPE relative
    /// positions stay correct (see [`KVCache::trim_front_keep_sink`] for
    /// the position invariant).
    ///
    /// Sliding-window models that manage their own internal
    /// `RotatingKVCache` go through a separate model-level code path and
    /// are unaffected. `None` (the default) preserves the legacy unbounded
    /// behaviour. Turbo-quantized caches (`Turbo4Asym` / `Turbo4` /
    /// `Turbo4Delegated` / `Turbo3Asym`) are skipped by
    /// [`KVCache::trim_front_keep_sink`] (which returns `0` for those
    /// modes) with a one-time startup warning logged in
    /// [`Self::with_max_kv_size`], the warning inspects both
    /// `kv_cache_mode` and the per-layer modes resolved from
    /// `batch_kv_quant` so the combination
    /// `--kv-quant-scheme=turboquant --max-kv-size=M` is flagged even
    /// when the legacy `--kv-cache-mode` flag is left at FP16.
    max_kv_size: Option<usize>,

    /// Context-retention policy at the KV bound (#1472, b10621
    /// `--context-shift` / `--keep`). With `context_shift` off (the default),
    /// [`Self::enforce_max_kv_size_for`] never trims: an over-long prompt is
    /// refused at admission and a decode that reaches the bound stops with
    /// `truncated: true`. With it on, the trim retains each sequence's
    /// resolved `keep` prefix and discards its resolved `discard` depth.
    context_retention: ContextRetentionPolicy,

    /// Experimental VLM prompt-prefix cache sharing toggle (#124 step c,
    /// `--enable-vlm-prefix-cache`).
    ///
    /// `false` (the default) keeps every multimodal request on the cold-prefill
    /// path (the pre-#124 behavior). When `true`, a multimodal chat request may
    /// adopt a previously donated KV prefix and donate its own, restricted to a
    /// whole-entry match so the prefilled suffix is the newly-appended text
    /// turn (multi-turn same-image conversations). Text-only and non-VLM
    /// requests are unaffected either way.
    enable_vlm_prefix_cache: bool,

    // -- Vision feature cache --
    /// Per-model vision feature cache bundle. Contains LRU caches for
    /// post-projection image features so multi-turn VLM conversations can
    /// skip the vision tower when the same image is referenced across turns.
    ///
    /// Stored as `Rc<..>` because the scheduler is single-threaded (all MLX
    /// work runs on the worker thread). The cache is cleared automatically
    /// when the scheduler (and thus this loaded model) is dropped.
    vision_caches: Rc<ModelVisionCaches>,

    // -- Axis B / — language-bias token map --
    /// Cached per-scheduler `TokenBiasMap` resolved once from the server-level
    /// `LangBiasConfig` at worker startup.
    ///
    /// **Phase 1 limitation — single policy per batch**: every sequence in
    /// this scheduler's active batch receives the same bias, regardless of
    /// per-request preferences. Per-sequence override via the
    /// `/v1/chat/completions` request body is reserved for a follow-up
    /// issue (B12) tracked outside this Epic. The bias is attached to each
    /// queued sequence's [`SamplingConfig`] at `enqueue_request` time so
    /// per-step sampling (`sample_token_optimized`) observes it with no
    /// additional hot-path overhead beyond the existing
    /// [`mlxcel_core::sampling::apply_token_bias`] fast path.
    ///
    /// Empty map = bit-exact baseline path (no sampling change, no alloc).
    token_bias: TokenBiasMap,
    /// Decoded text of every vocabulary token, filled lazily on the first
    /// DRY breaker-head derivation (#1485) and reused for every later
    /// breaker set.
    dry_vocab_texts: Option<std::sync::Arc<Vec<String>>>,
    /// Derived DRY breaker head maps keyed by breaker-string set (#1485):
    /// the server-wide default set is derived once and every request that
    /// inherits it hits this cache; per-request sets each pay one
    /// vocabulary scan. Bounded (cleared at 16 entries) because distinct
    /// sets are operator-driven, not attacker-driven state.
    dry_breaker_cache: std::collections::HashMap<
        Vec<String>,
        std::sync::Arc<std::collections::HashMap<i32, Vec<Vec<i32>>>>,
    >,

    /// Reserved output-illegal token ids for the loaded model (issue #350).
    ///
    /// Multimodal models (e.g. `gemma4_unified`) carry audio / image / video
    /// span placeholder ids that must never be emitted as text. Resolved once
    /// at construction from [`LanguageModel::output_suppressed_token_ids`] and
    /// force-masked to `-inf` on every sequence's sampling config at
    /// [`Self::enqueue_request`] time, unconditionally (suppression always
    /// wins over any per-request bias). Empty for non-multimodal models, which
    /// keeps the enqueue path zero-cost.
    model_output_suppressed: Vec<i32>,

    /// Tokenizer newline token id(s), resolved once at worker startup.
    ///
    /// Part of the XTC (Exclude Top Choices) special-token allowlist: at
    /// [`Self::enqueue_request`] time this is combined with the per-request
    /// merged end-of-sequence set and installed on
    /// `sampling.xtc_special_token_ids` so the filter can never remove a
    /// token needed to end a line or the sequence. Empty for tokenizers
    /// whose newline does not resolve (unlikely, but not fatal); the enqueue
    /// path only spends the merge cost when `sampling.xtc_probability > 0.0`.
    xtc_newline_token_ids: Vec<i32>,

    // -- — thinking-token budget --
    /// Server-wide default thinking-token budget. `None` means unrestricted.
    /// Per-request `thinking_budget_tokens` overrides this at enqueue time.
    reasoning_budget: Option<ThinkingBudget>,
    /// Cached `<think>` / `</think>` token id pair resolved once from the
    /// tokenizer at worker startup. `None` for non-thinking models; when
    /// `None`, every sequence's [`ThinkingState`] is constructed as disabled
    /// regardless of any budget configuration.
    thinking_token_ids: Option<ThinkingTokenIds>,

    // -- cross-request prompt-prefix KV cache --
    /// Shared store that hands out detached KV caches on prefix match and
    /// absorbs donated caches on sequence finish. `None` when the feature is
    /// disabled at config time so the hot path has zero overhead.
    prompt_cache: Option<Arc<PromptCacheStore>>,

    /// Parallel map indexed by `SequenceId`: remembers the
    /// [`PromptCacheRequestContext`] per in-flight sequence so the donate-back
    /// path on completion can rebuild the cache key without touching the HTTP
    /// request layer again. Dropped automatically when the sequence is
    /// removed from the map on finish / error.
    prompt_cache_seq_ctx: std::collections::HashMap<SequenceId, PromptCacheRequestContext>,

    /// Pending background prompt-cache warm-ups (issue #1144).
    ///
    /// Each entry is the next turn's expected history prefix for a conversation
    /// whose reply just finished. Bounded and newest-wins: a warm-up is an
    /// optimization for a turn that may never arrive, so under a backlog the
    /// freshest conversation is the one worth warming and the stale ones are
    /// dropped rather than queued behind it.
    prompt_cache_warmups: std::collections::VecDeque<(Vec<i32>, PromptCacheRequestContext)>,

    /// resolved speculative-decoding dispatch shape.
    ///
    /// Defaults to [`crate::server::SpeculativeDispatch::Disabled`]
    /// (constructed by [`Self::with_config`]). When the scheduler is
    /// driven by a worker that wires `--draft-model` /
    /// `--draft-kind` / `--draft-block-size`, the matching kind-specific
    /// variant is attached via
    /// [`Self::with_speculative_dispatch`].
    ///
    /// **Hot-path semantics**: every per-request decode-tick first
    /// inspects `self.speculative_dispatch` via [`Self::should_dispatch_speculative`].
    /// When the dispatch is `Disabled` (the default), the inspect is a
    /// single match-arm short-circuit so the bit-exact classic decode
    /// path stays zero-overhead. When the dispatch is a kind-specific
    /// variant AND the per-request preconditions hold (single active
    /// sequence, target supports the matching trait), the scheduler
    /// delegates to the speculative round-loop driver — see the
    /// per-kind dispatch hooks scheduled to land alongside this field.
    /// Until those hooks land, the field is plumbed end-to-end and the
    /// scheduler logs the auto-detected dispatch once at startup, but
    /// still falls back to classic decode at request time. This is the
    /// minimum-viable architectural foundation; full B=1 / B>1 decode
    /// integration completes in the peer follow-up sketched in the
    /// implementation plan.
    speculative_dispatch: crate::server::SpeculativeDispatch,

    /// lazy-loaded drafter handle for the speculative burst
    /// path. Constructed empty alongside the dispatch; the drafter's
    /// weights are loaded from disk on the **first** speculative
    /// request and cached for subsequent requests on the same worker
    /// (mandate 2). For
    /// [`crate::server::SpeculativeDispatch::Disabled`] this slot stays
    /// empty for the worker's lifetime and the burst path is never
    /// entered.
    speculative_drafter_slot: super::speculative_burst::WorkerDrafterSlot,

    /// Adaptive MTP enable/decline policy (issue #333). `Some` only when the
    /// dispatch is [`crate::server::SpeculativeDispatch::Mtp`] and the adaptive
    /// path is enabled (`MLXCEL_MTP_ADAPTIVE` not set to an off value); built
    /// by [`Self::with_mtp_policy`]. When `None` the B=1 MTP gate falls back to
    /// the static per-hardware default
    /// ([`super::speculative_burst::mtp_b1_burst_enabled`]). The policy profiles
    /// the first few B=1 bursts of the (target, drafter, hardware) pairing and
    /// settles to a data-driven verdict; consulted via
    /// [`super::mtp_policy::MtpPolicy::should_attempt_b1`] and fed via
    /// [`super::mtp_policy::MtpPolicy::record_b1_sample`].
    mtp_policy: Option<super::mtp_policy::MtpPolicy>,

    /// In-flight tick-cooperative B=1 MTP speculative slice (issue #734):
    /// the ACTIVE holder of the worker's single speculative slot. `Some`
    /// while a speculative request is being served one round per
    /// scheduler tick; the job owns the request's `SequenceInfo`, the
    /// generator's owned session state, and the (un-reset) drafter between
    /// ticks. At most one slice is ACTIVE at a time; further
    /// speculative-eligible requests either wait in
    /// [`Self::speculative_slice_backlog`] for a slot grant (issue #746)
    /// or fall back to classic decode (see
    /// [`Self::try_speculative_burst`]). Boxed: the job is fat
    /// (SequenceInfo + MLX handles) and this field is `None` for every
    /// non-speculative deployment.
    speculative_slice: Option<Box<super::speculative_slice::MtpSliceJob>>,

    /// Backlog of speculative work waiting for the single slice slot
    /// (issue #746): parked in-flight jobs (rotated out at a grant
    /// boundary, drafter returned to the worker slot) and admitted
    /// waiters (slice 0 not yet run) in ONE FIFO ring, granted priority
    /// lane first then FIFO, with a skip-cap anti-starvation floor
    /// ([`super::speculative_slice::next_grant_index`]). Bounded by
    /// [`super::speculative_slice::MTP_SLICE_BACKLOG_CAP`] at admission;
    /// a park transiently pushes the ring to CAP + 1 entries until the
    /// next promotion, so total live speculative sessions (the active
    /// job plus parked jobs and waiters, each holding its per-sequence
    /// KV) peak at CAP + 1 = 3. Empty for non-speculative deployments (a
    /// `VecDeque` allocates nothing until the first push). On scheduler
    /// shutdown the entries drop exactly like an in-flight
    /// `speculative_slice` job (response channels close and clients
    /// observe the hangup).
    speculative_slice_backlog:
        std::collections::VecDeque<super::speculative_slice::SliceBacklogEntry>,

    /// Slices the active job has executed in its CURRENT slot grant
    /// (issue #746), slice 0 included for an admission grant. When it
    /// reaches [`Self::speculative_slice_grant_budget`] AND the backlog
    /// is non-empty, the job is parked at the next round boundary
    /// ([`super::speculative_slice::slice_grant_expired`], checked at the
    /// tail of [`Self::execute_speculative_slice_round`]). Keeps counting
    /// while uncontended so contention appearing after an overrun rotates
    /// at the first round boundary.
    speculative_slice_grant_slices: usize,

    /// The `MLXCEL_MTP_SLICE_GRANT_ROUNDS` budget resolved ONCE at the
    /// start of the current grant (both grant-start sites: the
    /// slice-0 install in [`Self::start_mtp_slice_b1`] and the
    /// parked-job promotion), so the per-round expiry check costs a
    /// counter increment plus a comparison against this cached value
    /// instead of an env read (env var access takes std's process-wide
    /// ENV lock and allocates). Runtime tunability stays at the same
    /// per-request cadence as the `mtp_tick_slice_enabled()` gate.
    speculative_slice_grant_budget: usize,

    /// Fairness flag for the slice tick-arbitration
    /// ([`super::speculative_slice::slice_takes_tick`]): `true` when the
    /// previously executed action was a speculative round, so the next
    /// tick yields to the classic actions when they have work. Cleared by
    /// the `Prefill` / `Decode` arms. Gives strict round/classic
    /// alternation under contention.
    speculative_slice_yielded: bool,

    // -- Disaggregated serving-role handoff --
    /// Cached decode-model paged block geometry for cross-node KV handoff
    /// ([`crate::distributed::disaggregated::handoff_impl`]).
    ///
    /// Lazily probed on the first [`Self::ingest_sequence_handoff`] and reused
    /// for every later restore, so the one-token geometry probe runs at most
    /// once per worker. `None` until the first ingest. Wired to a live caller by
    /// the disaggregated decode serving role (a later step); the hooks below are
    /// the in-crate seam it builds on.
    #[allow(dead_code)]
    paged_handoff_geometry: Option<crate::distributed::kv_cache_serde::ExpectedBlockGeometry>,

    // -- Lookahead async_eval decode pipeline (issue #632) --
    /// Prebuilt next-step tokens for the active decode batch, scheduled with
    /// `async_eval` one tick ahead so the GPU forward overlaps the host-side
    /// commit / stop-check / next-tick bookkeeping. `None` outside a steady
    /// pipelined run (the bit-exact synchronous fallback). See
    /// [`DecodeLookahead`] and [`Self::execute_decode_step`] for the state
    /// machine and every invalidation trigger.
    decode_lookahead: Option<DecodeLookahead>,

    /// `MLXCEL_FORCE_SYNC` kill switch, read once at construction (mirrors the
    /// CLI generation loop's hoisted env probe). When `true` the scheduler
    /// never engages the lookahead pipeline and every decode tick runs
    /// synchronously, so the sync path stays available for A/B equivalence.
    lookahead_force_sync: bool,
}

/// One prebuilt decode step held across ticks by the lookahead pipeline.
///
/// The `tokens` array was sampled from a forward that has already been issued
/// (`async_eval`), and that forward appended exactly one KV position per
/// sequence (the last committed token). `tokens` themselves are NOT yet
/// committed and NOT yet in the KV cache. Tearing the pipeline down
/// (`discard_lookahead`) trims that one speculative KV position per sequence
/// and drops `tokens`, restoring the exact synchronous-decode cache invariant.
struct DecodeLookahead {
    /// Active sequence id set this step was built for, in batch order. The
    /// pipeline is only consumed when the next tick decodes this identical set.
    ids: Vec<SequenceId>,
    /// `[B]` device token-id array (uint32), one per `ids` entry, already
    /// scheduled with `async_eval`.
    tokens: UniquePtr<mlxcel_core::MlxArray>,
}

/// Copy a `[B]` device token-id array to host as `Vec<i32>`. `fused_sample`
/// returns a row-contiguous `uint32` array; the raw bytes are reinterpreted as
/// `i32`, exact for any token id in `0..vocab_size`.
///
/// Uses [`mlxcel_core::array_evaluated_bytes`] (surgical per-array `eval`, no
/// `contiguous()` op) rather than `array_to_raw_bytes`: the steady pipeline has
/// already scheduled the next forward on the same stream before this read, and
/// `array_to_raw_bytes`' `contiguous()` would enqueue a fresh op behind that
/// forward, making the read block on it and collapsing the overlap. This reader
/// waits only on the token array's own completion event.
fn lookahead_tokens_to_host(tokens: &mlxcel_core::MlxArray) -> Vec<i32> {
    let bytes = mlxcel_core::array_evaluated_bytes(tokens);
    bytes
        .chunks_exact(4)
        .map(|c| i32::from_ne_bytes([c[0], c[1], c[2], c[3]]))
        .collect()
}

/// Pure decision: may the lookahead pipeline stay engaged for the next tick?
///
/// False when the next tick would change batch membership: a queued request is
/// waiting to be admitted, a chunked prefill is interleaving, or a preemption is
/// pending. Extracted from [`BatchScheduler::lookahead_safe`] so unit tests can
/// exercise every invalidation trigger without constructing a live model.
fn lookahead_pipeline_safe(queue_empty: bool, chunked_in_progress: bool, preempting: bool) -> bool {
    queue_empty && !chunked_in_progress && !preempting
}

/// Pure decision: does committing `next_token` finish this sequence?
///
/// A finishing token (cancellation, an EOS / stop id, or the length limit) forces
/// the steady pipeline to discard its prebuilt step and re-run the tick
/// synchronously, so completion and prompt-cache donation always flow through the
/// untouched synchronous path from a clean cache state. Mirrors the per-row
/// pre-check in [`BatchScheduler::pipelined_steady_decode`].
fn lookahead_token_finishes(
    next_token: i32,
    generated_len: usize,
    max_tokens: usize,
    merged_eos: &[i32],
    cancelled: bool,
) -> bool {
    cancelled || merged_eos.contains(&next_token) || generated_len + 1 >= max_tokens
}

/// Number of speculative KV positions a lookahead teardown must unwind.
///
/// The steady tick issues step n+1's prime forward BEFORE it learns step n's
/// finish outcome, so a teardown after a successful prime (`next_prime_issued`)
/// must unwind two speculative appends (step n plus step n+1). A prime that
/// bailed (its forward returned `None`) or any teardown that runs before a prime
/// (admission, preemption, stale id set, cancellation in `finalize_completed`)
/// unwinds one (step n only). Mirrors the count selection in
/// [`BatchScheduler::pipelined_steady_decode`] and the `1`-position teardowns.
fn lookahead_teardown_positions(next_prime_issued: bool) -> usize {
    if next_prime_issued { 2 } else { 1 }
}

/// Pick the preemption victim for `policy` out of a candidate iterator.
///
/// This is the single implementation of the eviction policy.
/// [`BatchScheduler::select_eviction_victim`] is a thin wrapper over it, and
/// unit tests call it directly. The indirection exists because `BatchScheduler`
/// needs a real model to construct, so a test cannot reach the method: the two
/// pre-existing eviction tests worked around that by copying the selection
/// expression inline, and both copies then drifted from production by losing
/// the `structured.is_none()` guard. Extend the policy here, never at a call
/// site.
///
/// Sequences carrying a structured-output constraint are filtered out inside
/// this function rather than by the caller, so the exclusion cannot be lost by
/// a caller that forgets it. See [`BatchScheduler::select_eviction_victim`] for
/// why those sequences cannot be preempted.
///
/// # Tie-break: smallest `seq_id`
///
/// Both arms append `seq_id` so the order is total. `seq_id` is unique across
/// the batch (it is the `ActiveBatch` map key), so no two candidates can
/// compare equal and the victim can no longer be decided by `HashMap`
/// iteration order, which `RandomState` re-seeds per map instance. This is the
/// reachable case rather than a theoretical one: the primary key of the
/// `LongestFirst` arm is `generated_tokens.len()`, a small integer that
/// sequences admitted together and decoding in lockstep share routinely.
///
/// The direction is smallest-id-wins, and it is chosen for anti-starvation
/// rather than only for totality. `SequenceId` is handed out monotonically by
/// `CachePool`, and preemption reallocates its victim under a *fresh*, higher
/// id (see `BatchScheduler::try_evict_for_preemption`), so a large id marks a
/// sequence that was preempted recently. Preferring the smallest id therefore
/// rotates preemption onto sequences that have not been hit yet; preferring the
/// largest would keep re-picking the request that was just replayed.
/// `SequenceInfo::created_at` survives preemption and would give true arrival
/// order, but for that reason it points the other way: it would repeatedly
/// select the same oldest request. It is also an `Instant`, so it would still
/// need `seq_id` behind it to be total.
///
/// Because the two arms use opposite-facing selectors, they need
/// opposite-facing tie components to break the same direction:
/// `Iterator::max_by_key` returns the LAST maximum while `Iterator::min_by`
/// returns the FIRST minimum (`docs/code-guidelines.md`, "HashMap Iteration
/// Order").
pub(crate) fn select_eviction_victim_from<'a>(
    sequences: impl Iterator<Item = &'a SequenceInfo>,
    policy: PreemptionPolicy,
) -> Option<SequenceId> {
    let candidates = sequences.filter(|seq| seq.structured.is_none());
    match policy {
        // Evict the sequence with the most generated tokens. `seq_id` is the
        // component that makes this key a TOTAL order; without it, tied
        // sequences resolve through `HashMap` iteration order. Do not
        // simplify it away. It is wrapped in `Reverse` because `max_by_key`
        // takes the LAST maximum, and reversing the id is what makes the
        // SMALLEST id win, matching the `LowestPriority` arm below.
        PreemptionPolicy::LongestFirst => candidates
            .max_by_key(|seq| {
                (
                    seq.generated_tokens.len(),
                    std::cmp::Reverse(seq.seq_id.as_u64()),
                )
            })
            .map(|seq| seq.seq_id),
        // Evict the lowest-priority sequence; break ties by longest, then by
        // smallest `seq_id`. As above, `seq_id` is the component that makes
        // the comparator a TOTAL order and must not be simplified away. It is
        // compared ascending here because `min_by` takes the FIRST minimum.
        PreemptionPolicy::LowestPriority => candidates
            .min_by(|a, b| {
                a.priority
                    .cmp(&b.priority)
                    .then_with(|| b.generated_tokens.len().cmp(&a.generated_tokens.len()))
                    .then_with(|| a.seq_id.as_u64().cmp(&b.seq_id.as_u64()))
            })
            .map(|seq| seq.seq_id),
    }
}

fn validate_dense_detached_kv_modes_against_table(
    dense: &mlxcel_core::cache::DetachedCacheSet,
    expected: &[KVCacheMode],
) -> Result<(), String> {
    if expected.len() != dense.num_layers() {
        return Err(format!(
            "resolved {} KV cache layer modes for {} detached layers",
            expected.len(),
            dense.num_layers()
        ));
    }
    for (idx, (detached, expected_mode)) in dense
        .caches
        .iter()
        .zip(expected.iter().copied())
        .enumerate()
    {
        let actual = detached.mode();
        if actual != expected_mode {
            return Err(format!(
                "layer {idx} detached mode {actual} does not match resolved mode {expected_mode}"
            ));
        }
    }
    Ok(())
}

mod admission;
mod config;
mod decode_tick;
mod handoff;
#[path = "../scheduler.rs"]
mod mtp_dispatch;
mod paged_layout;
mod prefill;
mod prompt_cache;
mod run_loop;
mod speculative_finalize;

#[cfg(test)]
mod structure_tests;

#[cfg(test)]
#[path = "../scheduler_tests.rs"]
mod tests;

#[cfg(test)]
#[path = "../serving_handoff_parity_tests.rs"]
mod serving_handoff_parity_tests;

#[cfg(test)]
#[path = "../scheduler_cohort_parity_tests.rs"]
mod scheduler_cohort_parity_tests;

#[cfg(test)]
#[path = "../scheduler_seed_determinism_tests.rs"]
mod scheduler_seed_determinism_tests;

#[cfg(test)]
#[path = "../scheduler_muse_glimmer_tests.rs"]
mod scheduler_muse_glimmer_tests;

#[cfg(test)]
#[path = "../scheduler_muse_glimmer_support.rs"]
mod scheduler_muse_glimmer_support;

#[cfg(test)]
#[path = "../scheduler_muse_glimmer_parallel_tests.rs"]
mod scheduler_muse_glimmer_parallel_tests;

#[cfg(test)]
#[path = "../scheduler_model_owned_cache_tests.rs"]
mod scheduler_model_owned_cache_tests;

/// Resolve a request's context-retention values against the server policy
/// (#1472), pure so the arithmetic is unit-testable without a scheduler.
///
/// Mirrors b10621's slot shift setup (`server-context.cpp`): the request's
/// `n_keep` falls back to the server-wide `--keep`, `-1` resolves to the
/// whole prompt, and one token is added on top when the tokenizer prepended a
/// BOS (`if (add_bos_token) n_keep += 1`), so "keep N prompt tokens" keeps N
/// tokens of the operator's prompt.
fn resolve_retention_values(
    policy: ContextRetentionPolicy,
    request: crate::server::config::RetentionOverride,
    prompt_len: usize,
    bos_prepended: bool,
) -> SequenceRetention {
    let requested = request.n_keep.unwrap_or(policy.n_keep);
    let mut keep: i64 = if requested < 0 {
        prompt_len as i64
    } else {
        requested
    };
    if bos_prepended {
        keep += 1;
    }
    SequenceRetention {
        keep,
        discard: request.n_discard.unwrap_or(0).max(0),
        context_exhausted: false,
    }
}

/// How many tokens a context shift discards (#1472), pure for unit testing.
///
/// `excess` is how far the live window overshot the bound (chunked prefill
/// can overshoot by a whole chunk). The requested depth (`n_discard`, or half
/// of the non-retained window at upstream's `0` default) is raised to at
/// least the excess so the bound is restored, and capped at `n_left - 1` so a
/// token always remains to decode from; `keep` is already clamped to
/// `bound - 4` by the caller, which keeps `n_left > excess` and the two
/// bounds compatible.
fn context_shift_trim_depth(live_len: i32, excess: i32, keep: i32, requested_discard: i32) -> i32 {
    let n_left = live_len - keep;
    let discard = if requested_discard > 0 {
        requested_discard
    } else {
        n_left / 2
    };
    discard.max(excess).min((n_left - 1).max(excess))
}
