import React, { useEffect, useState } from 'react';
import { Button, Dialog, ErrorBanner, Field, Select } from '../../design-system/primitives';
import type { CatalogEntry, LoadProfile } from '../../api/types';
import { t, type Locale } from '../../i18n/catalog';
import { KV_MODES, profileCli, useLoadProfile, validateLoadProfile } from './load-profiles';
export function ProfileSettings({ model, locale, single }: { model: CatalogEntry | null; locale: Locale; single: boolean }): React.JSX.Element {
  const store = useLoadProfile(model?.identity.id ?? null);
  const [draft, setDraft] = useState<LoadProfile>(store.profile);
  const [scope, setScope] = useState<'model' | 'reusable'>(model === null ? 'reusable' : 'model');
  const [transfer, setTransfer] = useState('');
  const [message, setMessage] = useState('');
  const [resetOpen, setResetOpen] = useState(false);
  const scopedProfile = scope === 'reusable' ? store.reusable : store.modelProfile;
  useEffect(() => { setDraft(scopedProfile); }, [scopedProfile]);
  const run = (action: () => void): void => { try { action(); setMessage(t(locale, 'settings.profile.saved')); } catch (error) { setMessage(error instanceof Error ? error.message : t(locale, 'settings.profile.failed')); } };
  return <section className="screen-stack"><h2>{t(locale, 'settings.profile.title')}</h2><p>{t(locale, 'settings.profile.body')}</p>{single ? <ErrorBanner tone="info" title={t(locale, 'settings.profile.single.title')} body={t(locale, 'settings.profile.single.body')} /> : null}<Select locale={locale} label={t(locale, 'settings.profile.scope')} value={scope} onChange={(value) => setScope(value as 'model' | 'reusable')} options={[{ value: 'reusable', label: t(locale, 'settings.profile.scope.reusable') }, ...(model === null ? [] : [{ value: 'model', label: model.identity.display_name }])]} /><div className="settings-grid"><Field label="ctx_size (1–262144)" value={draft.ctx_size?.toString() ?? ''} onChange={(raw) => setDraft({ ...draft, ctx_size: raw.trim() === '' ? undefined : Number(raw) })} hint={t(locale, 'settings.profile.ctx_hint')} /><Field label="n_parallel (1–32)" value={draft.n_parallel?.toString() ?? ''} onChange={(raw) => setDraft({ ...draft, n_parallel: raw.trim() === '' ? undefined : Number(raw) })} hint={t(locale, 'settings.profile.parallel_hint')} /><Select locale={locale} label="kv_cache_mode" value={draft.kv_cache_mode ?? ''} onChange={(value) => setDraft({ ...draft, kv_cache_mode: value === '' ? undefined : value as NonNullable<LoadProfile['kv_cache_mode']> })} options={[{ value: '', label: t(locale, 'settings.profile.inherit') }, ...KV_MODES.map((value) => ({ value, label: value }))]} /></div><p>{t(locale, 'settings.profile.restrictions')}</p>{message ? <ErrorBanner tone="info" title={t(locale, 'settings.profile.result_title')} body={message} /> : null}<div><Button onClick={() => run(() => store.save(validateLoadProfile(draft), scope))}>{t(locale, 'settings.profile.save')}</Button> <Button onClick={() => { setDraft(scopedProfile); setMessage(''); }}>{t(locale, 'settings.profile.discard')}</Button> <Button onClick={() => setResetOpen(true)}>{t(locale, 'settings.profile.reset_open')}</Button></div><p>{t(locale, 'settings.profile.saved_pending')}: <code>{JSON.stringify(scopedProfile)}</code></p><p>{t(locale, 'settings.profile.cli')}</p><code>{profileCli(scopedProfile)}</code><details><summary>{t(locale, 'settings.profile.transfer')}</summary><label className="ds-field"><span>{t(locale, 'settings.profile.transfer.label')}</span><textarea value={transfer} onChange={(event) => setTransfer(event.currentTarget.value)} maxLength={65536} rows={6} /></label><Button onClick={() => setTransfer(store.exportJson())}>{t(locale, 'settings.profile.transfer.export')}</Button> <Button onClick={() => run(() => store.importJson(transfer))}>{t(locale, 'settings.profile.transfer.import')}</Button></details><Dialog open={resetOpen} title={t(locale, 'settings.profile.reset.title')} closeLabel={t(locale, 'common.close')} onClose={() => setResetOpen(false)}><p>{t(locale, 'settings.profile.reset.body')}</p><Button onClick={() => { run(() => store.reset(scope)); setResetOpen(false); }}>{t(locale, 'settings.profile.reset.confirm')}</Button></Dialog></section>;
}
