// Copyright 2026 Lablup Inc. Licensed under the Apache License, Version 2.0.
// Settings copy for request defaults, live server values, next-load profiles and
// observed context. Every entry is mirrored in tests/fixtures/webui/strings.json.
const settingsBaseStrings = [
  { key: 'settings.server.privacy.body', en: 'Appearance and explicitly saved load profiles use this browser’s preferences. Request defaults stay in memory; API credentials and system prompts are never stored by Settings. Conversation history is controlled separately in Chat.', ko: '모양과 명시적으로 저장한 로드 프로필은 브라우저 환경설정을 사용합니다. 요청 기본값은 메모리에만 유지하며 API 자격 증명과 시스템 프롬프트는 설정에서 저장하지 않습니다. 대화 기록은 대화 화면에서 별도로 관리합니다.', test_id: 'settings-server-privacy-body' },
  { key: 'settings.server.unavailable.title', en: 'Server controls unavailable', ko: '서버 제어 사용 불가', test_id: 'settings-server-unavailable-title' },
  { key: 'settings.server.unavailable.body', en: 'Connect from Models or Chat, or refresh the connection before changing server settings. Browser appearance and request defaults remain available. Schema mismatch disables server controls.', ko: '모델이나 대화 화면에서 연결하거나 연결을 새로 고친 후 서버 설정을 변경하세요. 브라우저 모양과 요청 기본값은 계속 사용할 수 있습니다. 스키마 불일치 시 서버 제어가 비활성화됩니다.', test_id: 'settings-server-unavailable-body' },
  { key: 'settings.server.model', en: 'Selected model for settings', ko: '설정 대상 모델', test_id: 'settings-server-model' },
  { key: 'settings.server.model.none', en: 'No model selected', ko: '선택한 모델 없음', test_id: 'settings-server-model-none' },
  { key: 'settings.server.model.hint', en: 'Selection changes browser context only. It never loads, unloads or reroutes an existing request.', ko: '선택은 브라우저 문맥만 변경하며 모델을 로드하거나 언로드하거나 기존 요청의 대상을 변경하지 않습니다.', test_id: 'settings-server-model-hint' },
  { key: 'settings.server.context.title', en: 'Effective context · observed, not estimated', ko: '실제 컨텍스트 · 추정이 아닌 관측값', test_id: 'settings-server-context-title' },
  { key: 'settings.server.context.n_ctx', en: 'Per-slot context tokens (/props n_ctx)', ko: '슬롯별 컨텍스트 토큰 (/props n_ctx)', test_id: 'settings-server-context-n-ctx' },
  { key: 'settings.server.context.n_ctx_hint', en: 'Zero/missing is unknown; do not multiply this value into a shared-pool capacity. Unified KV remains separate work (#1815).', ko: '0 또는 누락은 알 수 없음입니다. 이 값에 슬롯 수를 곱해 공유 풀 용량으로 간주하지 않습니다. 통합 KV는 별도 작업입니다 (#1815).', test_id: 'settings-server-context-n-ctx-hint' },
  { key: 'settings.server.context.slots', en: 'Configured slots (/props total_slots)', ko: '설정된 슬롯 (/props total_slots)', test_id: 'settings-server-context-slots' },
  { key: 'settings.server.context.kv_mode', en: 'Active resolved KV cache mode (/props)', ko: '현재 실제 KV 캐시 모드 (/props)', test_id: 'settings-server-context-kv-mode' },
  { key: 'settings.server.context.geometry', en: 'Reported context geometry', ko: '보고된 컨텍스트 구성', test_id: 'settings-server-context-geometry' },
  { key: 'settings.server.context.geometry_unknown', en: 'Unknown / props disabled or unavailable', ko: '알 수 없음 / props 비활성화 또는 사용 불가', test_id: 'settings-server-context-geometry-unknown' },
  { key: 'settings.server.unknown', en: 'Unknown', ko: '알 수 없음', test_id: 'settings-server-unknown' },
  { key: 'settings.server.no_model.title', en: 'No ready model selected', ko: '준비된 모델이 선택되지 않음', test_id: 'settings-server-no-model-title' },
  { key: 'settings.server.no_model.body', en: 'Selection never loads a model. Load explicitly from Models to read live settings.', ko: '모델 선택은 로드를 수행하지 않습니다. 모델 화면에서 명시적으로 로드하여 실시간 설정을 확인하세요.', test_id: 'settings-server-no-model-body' },
  { key: 'settings.server.live_disabled.title', en: 'Live settings disabled by operator', ko: '운영자가 실시간 설정을 비활성화함', test_id: 'settings-server-live-disabled-title' },
  { key: 'settings.server.live_disabled.body', en: 'Restart with --settings to enable this endpoint. WebUI never enables settings, props, metrics or slots implicitly.', ko: '엔드포인트를 활성화하려면 --settings로 재시작하세요. WebUI는 settings, props, metrics 또는 slots를 자동으로 활성화하지 않습니다.', test_id: 'settings-server-live-disabled-body' },
  { key: 'settings.generation.title', en: 'Generation · next request', ko: '생성 · 다음 요청', test_id: 'settings-generation-title' },
  { key: 'settings.generation.body', en: 'These defaults stay in browser memory only. Blank fields are omitted and inherit server defaults. Existing turns are frozen; changing defaults never alters an in-flight request. System prompts belong to individual conversations in Chat and are not stored here.', ko: '기본값은 브라우저 메모리에만 남습니다. 빈 필드는 생략되어 서버 기본값을 사용합니다. 진행 중인 요청은 변경되지 않습니다. 시스템 프롬프트는 대화 화면의 개별 대화에서 설정하며 여기에 저장하지 않습니다.', test_id: 'settings-generation-body' },
  { key: 'settings.generation.invalid', en: 'Invalid defaults', ko: '잘못된 기본값', test_id: 'settings-generation-invalid' },
  { key: 'settings.generation.error_title', en: 'Invalid request defaults', ko: '잘못된 요청 기본값', test_id: 'settings-generation-error-title' },
  { key: 'settings.generation.save', en: 'Save session defaults', ko: '세션 기본값 저장', test_id: 'settings-generation-save' },
  { key: 'settings.generation.reset_open', en: 'Reset request defaults…', ko: '요청 기본값 초기화…', test_id: 'settings-generation-reset-open' },
  { key: 'settings.generation.reset.title', en: 'Reset request defaults?', ko: '요청 기본값을 초기화할까요?', test_id: 'settings-generation-reset-title' },
  { key: 'settings.generation.reset.body', en: 'Only browser-session request defaults will be cleared. Server and next-load profiles remain unchanged.', ko: '브라우저 세션 요청 기본값만 지워집니다. 서버와 다음 로드 프로필은 변경되지 않습니다.', test_id: 'settings-generation-reset-body' },
  { key: 'settings.generation.reset.confirm', en: 'Reset request defaults', ko: '요청 기본값 초기화', test_id: 'settings-generation-reset-confirm' },
  { key: 'settings.live.title', en: 'Loaded model · live server values', ko: '로드된 모델 · 실시간 서버 값', test_id: 'settings-live-title' },
  { key: 'settings.live.body', en: 'Changes affect newly admitted requests. Fingerprints detect already-observed external changes, not atomic compare-and-swap. Numeric bounds remain enforced by the server; this schema publishes types and allowed enums, not numeric min/max.', ko: '변경은 새로 수락되는 요청에 적용됩니다. 지문은 관측된 외부 변경을 감지하지만 원자적 비교 교환은 아닙니다. 숫자 범위는 서버가 검증합니다. 스키마에는 타입과 허용 열거값만 있습니다.', test_id: 'settings-live-body' },
  { key: 'settings.live.unavailable', en: 'Settings unavailable. The server may have disabled --settings.', ko: '설정을 사용할 수 없습니다. 서버에서 --settings가 비활성화되었을 수 있습니다.', test_id: 'settings-live-unavailable' },
  { key: 'settings.live.refreshed', en: 'Current values refreshed. Review the retained draft before applying.', ko: '현재 값을 새로 고쳤습니다. 남아 있는 초안을 검토한 후 적용하세요.', test_id: 'settings-live-refreshed' },
  { key: 'settings.live.refresh_failed', en: 'Refresh failed. No changes submitted.', ko: '새로 고침에 실패했습니다. 변경 사항은 전송되지 않았습니다.', test_id: 'settings-live-refresh-failed' },
  { key: 'settings.live.invalid_value', en: 'Invalid value', ko: '잘못된 값', test_id: 'settings-live-invalid-value' },
  { key: 'settings.live.conflict', en: 'Another client changed these settings. Current values refreshed; review and Apply again to reconfirm.', ko: '다른 클라이언트가 설정을 변경했습니다. 갱신된 현재 값을 검토하고 다시 적용하여 확인하세요.', test_id: 'settings-live-conflict' },
  { key: 'settings.live.partial', en: '{applied} applied; {rejected} rejected. Rejected drafts retained.', ko: '{applied}개 적용, {rejected}개 거부됨. 거부된 초안은 유지됩니다.', test_id: 'settings-live-partial' },
  { key: 'settings.live.applied', en: 'Accepted fields applied; reading effective values.', ko: '승인된 필드를 적용했습니다. 실제 값을 다시 읽습니다.', test_id: 'settings-live-applied' },
  { key: 'settings.live.unknown_outcome', en: 'The outcome may be unknown. Refresh effective values before retrying; no automatic PATCH retry.', ko: '결과를 확정할 수 없습니다. 재시도 전에 실제 값을 새로 고치세요. PATCH는 자동 재시도하지 않습니다.', test_id: 'settings-live-unknown-outcome' },
  { key: 'settings.live.result_title', en: 'Settings result', ko: '설정 결과', test_id: 'settings-live-result-title' },
  { key: 'settings.live.refresh', en: 'Refresh current values', ko: '현재 값 새로 고침', test_id: 'settings-live-refresh' },
  { key: 'settings.live.apply', en: 'Apply live draft', ko: '실시간 초안 적용', test_id: 'settings-live-apply' },
  { key: 'settings.live.reset_open', en: 'Reset live draft…', ko: '실시간 초안 초기화…', test_id: 'settings-live-reset-open' },
  { key: 'settings.live.startup', en: 'Server startup · restart required (read-only)', ko: '서버 시작 · 재시작 필요 (읽기 전용)', test_id: 'settings-live-startup' },
  { key: 'settings.live.reset.title', en: 'Reset live draft only?', ko: '실시간 초안만 초기화할까요?', test_id: 'settings-live-reset-title' },
  { key: 'settings.live.reset.body', en: 'Stage server startup defaults for mutable fields. No server change occurs until Apply.', ko: '변경 가능한 필드에 서버 시작 기본값을 초안으로 설정합니다. 적용 전에는 서버가 변경되지 않습니다.', test_id: 'settings-live-reset-body' },
  { key: 'settings.live.reset.confirm', en: 'Reset draft', ko: '초안 초기화', test_id: 'settings-live-reset-confirm' },
  { key: 'settings.profile.title', en: 'Next load · browser profile', ko: '다음 로드 · 브라우저 프로필', test_id: 'settings-profile-title' },
  { key: 'settings.profile.body', en: 'Explicit CLI settings take precedence over this profile; the profile overrides a preset only where CLI has not pinned a value. Effective resolved values must be read after loading. Saving is not loading. A loaded model requires an explicit unload and load from Models; failed loads retain this pending profile.', ko: '명시적 CLI 설정이 프로필보다 우선합니다. CLI로 고정되지 않은 값에만 프로필이 프리셋보다 우선합니다. 실제 값은 로드 후 확인하세요. 저장은 로드가 아닙니다. 로드된 모델은 모델 화면에서 명시적으로 언로드 후 로드해야 하며, 실패 시 프로필은 대기 상태로 남습니다.', test_id: 'settings-profile-body' },
  { key: 'settings.profile.saved', en: 'Browser profile saved. Nothing loaded or changed on the server.', ko: '브라우저 프로필을 저장했습니다. 서버에서 로드하거나 변경한 내용은 없습니다.', test_id: 'settings-profile-saved' },
  { key: 'settings.profile.failed', en: 'Profile operation failed', ko: '프로필 작업에 실패했습니다', test_id: 'settings-profile-failed' },
  { key: 'settings.profile.single.title', en: 'Single-model mode: restart required', ko: '단일 모델 모드: 재시작 필요', test_id: 'settings-profile-single-title' },
  { key: 'settings.profile.single.body', en: 'These preferences cannot be applied to this running worker. Restart with validated CLI flags, or start model-free mode to use load operations.', ko: '실행 중인 워커에 적용할 수 없습니다. 검증된 CLI 플래그로 재시작하거나 모델 없는 모드에서 로드 작업을 사용하세요.', test_id: 'settings-profile-single-body' },
  { key: 'settings.profile.scope', en: 'Profile scope', ko: '프로필 범위', test_id: 'settings-profile-scope' },
  { key: 'settings.profile.scope.reusable', en: 'Reusable defaults', ko: '재사용 기본값', test_id: 'settings-profile-scope-reusable' },
  { key: 'settings.profile.ctx_hint', en: 'Blank: inherit. Actual per-slot context is resolved by the server, not estimated here.', ko: '빈 값: 상속. 슬롯별 실제 컨텍스트는 서버가 결정하며 여기서 추정하지 않습니다.', test_id: 'settings-profile-ctx-hint' },
  { key: 'settings.profile.parallel_hint', en: 'Scheduler/worker geometry changes only on the next explicit load.', ko: '스케줄러/워커 구성은 다음 명시적 로드에서만 변경됩니다.', test_id: 'settings-profile-parallel-hint' },
  { key: 'settings.profile.inherit', en: 'Inherit', ko: '상속', test_id: 'settings-profile-inherit' },
  { key: 'settings.profile.result_title', en: 'Profile result', ko: '프로필 결과', test_id: 'settings-profile-result-title' },
  { key: 'settings.profile.save', en: 'Save pending profile', ko: '대기 프로필 저장', test_id: 'settings-profile-save' },
  { key: 'settings.profile.discard', en: 'Discard draft', ko: '초안 취소', test_id: 'settings-profile-discard' },
  { key: 'settings.profile.reset_open', en: 'Reset selected profile…', ko: '선택 프로필 초기화…', test_id: 'settings-profile-reset-open' },
  { key: 'settings.profile.saved_pending', en: 'Saved pending profile (not active)', ko: '저장된 대기 프로필 (미적용)', test_id: 'settings-profile-saved-pending' },
  { key: 'settings.profile.cli', en: 'Sanitized CLI flags · display only; model source omitted', ko: '안전한 CLI 플래그 · 표시 전용; 모델 소스 생략', test_id: 'settings-profile-cli' },
  { key: 'settings.profile.transfer', en: 'Import / export browser profiles', ko: '브라우저 프로필 가져오기 / 내보내기', test_id: 'settings-profile-transfer' },
  { key: 'settings.profile.transfer.label', en: 'Versioned profile JSON', ko: '버전이 있는 프로필 JSON', test_id: 'settings-profile-transfer-label' },
  { key: 'settings.profile.transfer.export', en: 'Export to text', ko: '텍스트로 내보내기', test_id: 'settings-profile-transfer-export' },
  { key: 'settings.profile.transfer.import', en: 'Validate and import', ko: '검증 후 가져오기', test_id: 'settings-profile-transfer-import' },
  { key: 'settings.profile.reset.title', en: 'Reset this browser profile?', ko: '이 브라우저 프로필을 초기화할까요?', test_id: 'settings-profile-reset-title' },
  { key: 'settings.profile.reset.body', en: 'Resets only the selected scope. Model scope falls back to reusable defaults; reusable scope leaves model-specific profiles intact. Does not change a running worker.', ko: '선택한 범위만 초기화합니다. 모델 범위는 재사용 기본값으로 돌아가며 재사용 범위는 모델별 프로필을 유지합니다. 실행 중인 워커는 변경하지 않습니다.', test_id: 'settings-profile-reset-body' },
  { key: 'settings.profile.reset.confirm', en: 'Reset profile', ko: '프로필 초기화', test_id: 'settings-profile-reset-confirm' },
  { key: 'settings.context_check.label', en: 'Optional raw prompt budget check', ko: '선택적 원시 프롬프트 예산 확인', test_id: 'settings-context-check-label' },
  { key: 'settings.context_check.hint', en: 'Sent only when Check is pressed; never persisted. Raw tokens exclude chat templates, conversation history and media. Server validation is final.', ko: '확인을 누를 때만 전송하며 저장하지 않습니다. 원시 토큰은 대화 템플릿, 대화 기록, 미디어를 제외합니다. 최종 검증은 서버가 수행합니다.', test_id: 'settings-context-check-hint' },
  { key: 'settings.context_check.check', en: 'Check with model tokenizer', ko: '모델 토크나이저로 확인', test_id: 'settings-context-check-check' },
  { key: 'settings.context_check.unavailable', en: 'Tokenization unavailable; budget unknown.', ko: '토큰화 불가; 예산을 알 수 없습니다.', test_id: 'settings-context-check-unavailable' },
  { key: 'settings.context_check.not_measured', en: 'Not measured', ko: '측정하지 않음', test_id: 'settings-context-check-not-measured' },
  { key: 'settings.context_check.count', en: '{count} raw tokens. {verdict}', ko: '{count} 원시 토큰. {verdict}', test_id: 'settings-context-check-count' },
  { key: 'settings.context_check.exceeds', en: 'Raw input + requested output already exceeds observed context.', ko: '원시 입력 + 요청 출력이 관측 컨텍스트를 초과합니다.', test_id: 'settings-context-check-exceeds' },
  { key: 'settings.context_check.unknown', en: 'Context/output is unknown; no fit claim.', ko: '컨텍스트/출력을 알 수 없어 수용 가능 여부를 판단하지 않습니다.', test_id: 'settings-context-check-unknown' },
  { key: 'settings.context_check.fits', en: 'Raw input + output fits, but templated chat may still exceed the context.', ko: '원시 입력 + 출력은 들어가지만 템플릿이 적용된 대화는 컨텍스트를 초과할 수 있습니다.', test_id: 'settings-context-check-fits' },
  { key: 'settings.sections', en: 'Settings sections', ko: '설정 섹션', test_id: 'settings-sections' },
  { key: 'settings.section.appearance', en: 'Appearance', ko: '화면 표시', test_id: 'settings-section-appearance' },
  { key: 'settings.section.requests', en: 'Requests', ko: '요청', test_id: 'settings-section-requests' },
  { key: 'settings.section.model', en: 'Model', ko: '모델', test_id: 'settings-section-model' },
  { key: 'settings.section.server', en: 'Server', ko: '서버', test_id: 'settings-section-server' },
  { key: 'settings.section.requests.description', en: 'Defaults for the next request from this browser. Memory only; blank fields inherit.', ko: '이 브라우저에서 보내는 다음 요청의 기본값입니다. 메모리에만 유지되며 빈 필드는 상속합니다.', test_id: 'settings-section-requests-description' },
  { key: 'settings.section.model.description', en: 'Next-load profile and live values for the selected model.', ko: '선택한 모델의 다음 로드 프로필과 실시간 값입니다.', test_id: 'settings-section-model-description' },
  { key: 'settings.section.server.description', en: 'Read-only values fixed when the server started, and the observed context.', ko: '서버 시작 시 고정된 읽기 전용 값과 관측된 컨텍스트입니다.', test_id: 'settings-section-server-description' },
  { key: 'settings.help.storage', en: 'About Settings storage', ko: '설정 저장 방식 안내', test_id: 'settings-help-storage' },
  { key: 'settings.help.requests', en: 'About request defaults', ko: '요청 기본값 안내', test_id: 'settings-help-requests' },
  { key: 'settings.help.profile', en: 'About next-load profiles', ko: '다음 로드 프로필 안내', test_id: 'settings-help-profile' },
  { key: 'settings.help.live', en: 'About live values', ko: '실시간 값 안내', test_id: 'settings-help-live' },
  { key: 'settings.help.context', en: 'About the effective context', ko: '실제 컨텍스트 안내', test_id: 'settings-help-context' },
  { key: 'settings.requests.effective', en: 'Next request: {value}', ko: '다음 요청: {value}', test_id: 'settings-requests-effective' },
  { key: 'settings.requests.value_source', en: '{value} ({source})', ko: '{value} ({source})', test_id: 'settings-requests-value-source' },
  { key: 'settings.requests.source.override', en: 'next-turn override', ko: '다음 턴 재정의', test_id: 'settings-requests-source-override' },
  { key: 'settings.requests.source.session', en: 'session default', ko: '세션 기본값', test_id: 'settings-requests-source-session' },
  { key: 'settings.requests.source.server', en: 'server default', ko: '서버 기본값', test_id: 'settings-requests-source-server' },
  { key: 'settings.requests.unknown', en: 'server default, not readable', ko: '서버 기본값, 읽을 수 없음', test_id: 'settings-requests-unknown' },
  { key: 'settings.requests.server_from', en: 'Server defaults read from {model}.', ko: '{model}에서 서버 기본값을 읽었습니다.', test_id: 'settings-requests-server-from' },
  { key: 'settings.requests.server_loading', en: 'Reading server defaults from {model}…', ko: '{model}에서 서버 기본값을 읽는 중…', test_id: 'settings-requests-server-loading' },
  { key: 'settings.requests.server_failed', en: 'Server defaults could not be read from {model}.', ko: '{model}에서 서버 기본값을 읽지 못했습니다.', test_id: 'settings-requests-server-failed' },
  { key: 'settings.requests.server_none', en: 'No ready model selected, so server defaults are not readable.', ko: '준비된 모델이 선택되지 않아 서버 기본값을 읽을 수 없습니다.', test_id: 'settings-requests-server-none' },
  { key: 'settings.requests.server_disabled', en: 'Live settings are disabled, so server defaults are not readable.', ko: '실시간 설정이 비활성화되어 서버 기본값을 읽을 수 없습니다.', test_id: 'settings-requests-server-disabled' },
  { key: 'settings.requests.server_offline', en: 'Not connected, so server defaults are not readable.', ko: '연결되지 않아 서버 기본값을 읽을 수 없습니다.', test_id: 'settings-requests-server-offline' },
  { key: 'settings.value.unset', en: 'not set', ko: '설정 안 됨', test_id: 'settings-value-unset' },
  { key: 'settings.control.unset', en: 'Leave unset', ko: '설정하지 않음', test_id: 'settings-control-unset' },
  { key: 'settings.control.invalid_json', en: 'Enter valid JSON', ko: '올바른 JSON을 입력하세요', test_id: 'settings-control-invalid-json' },
  { key: 'settings.control.not_allowed', en: '{value} (not an allowed value)', ko: '{value} (허용되지 않는 값)', test_id: 'settings-control-not-allowed' },
  { key: 'settings.control.server_value', en: 'Server value: {value}', ko: '서버 값: {value}', test_id: 'settings-control-server-value' },
  { key: 'settings.live.group.sampling', en: 'Sampling', ko: '샘플링', test_id: 'settings-live-group-sampling' },
  { key: 'settings.live.group.dry', en: 'DRY', ko: 'DRY', test_id: 'settings-live-group-dry' },
  { key: 'settings.live.group.diffusion', en: 'Diffusion', ko: '디퓨전', test_id: 'settings-live-group-diffusion' },
  { key: 'settings.live.group.template', en: 'Template', ko: '템플릿', test_id: 'settings-live-group-template' },
  { key: 'settings.live.group.other', en: 'Other', ko: '기타', test_id: 'settings-live-group-other' },
  { key: 'settings.profile.ctx_size', en: 'Context size (1–262144)', ko: '컨텍스트 크기 (1–262144)', test_id: 'settings-profile-ctx-size' },
  { key: 'settings.profile.n_parallel', en: 'Parallel slots (1–32)', ko: '병렬 슬롯 (1–32)', test_id: 'settings-profile-n-parallel' },
  { key: 'settings.profile.kv_cache_mode', en: 'KV cache mode', ko: 'KV 캐시 모드', test_id: 'settings-profile-kv-cache-mode' },
  { key: 'settings.profile.show_cli', en: 'Show as CLI flags', ko: 'CLI 플래그로 보기', test_id: 'settings-profile-show-cli' },
  { key: 'settings.profile.copy', en: 'Copy flags', ko: '플래그 복사', test_id: 'settings-profile-copy' },
  { key: 'settings.profile.copied', en: 'CLI flags copied.', ko: 'CLI 플래그를 복사했습니다.', test_id: 'settings-profile-copied' },
  { key: 'settings.profile.copy_failed', en: 'Copy failed. Select the flags and copy them instead.', ko: '복사하지 못했습니다. 플래그를 선택해 직접 복사하세요.', test_id: 'settings-profile-copy-failed' },
  { key: 'settings.server.startup.reasons', en: 'Why these values are read-only', ko: '읽기 전용인 이유', test_id: 'settings-server-startup-reasons' },
  { key: 'settings.server.props_unavailable.title', en: 'Context unavailable', ko: '컨텍스트를 확인할 수 없음', test_id: 'settings-server-props-unavailable-title' },
  { key: 'settings.server.props_unavailable.body', en: 'The model did not answer /props. Restart with --props to observe its context.', ko: '모델이 /props에 응답하지 않았습니다. 컨텍스트를 확인하려면 --props로 재시작하세요.', test_id: 'settings-server-props-unavailable-body' },
  { key: 'settings.server.startup.failed', en: 'Startup values unavailable', ko: '시작 값을 확인할 수 없음', test_id: 'settings-server-startup-failed' },
] as const;

// Labels and help the UI owns for known live settings, in both locales. A schema name
// missing here shows its raw key and the server's English help instead.
const liveSettingStrings = [
  { key: 'settings.live.timeout_seconds', en: 'Decode timeout (seconds)', ko: '디코드 제한 시간(초)', test_id: 'settings-live-timeout-seconds' },
  { key: 'settings.live.timeout_seconds.help', en: 'Decode watchdog used by newly admitted requests.', ko: '새로 수락되는 요청에 적용되는 디코드 감시 시간입니다.', test_id: 'settings-live-timeout-seconds-help' },
  { key: 'settings.live.default_temperature', en: 'Temperature', ko: '온도', test_id: 'settings-live-default-temperature' },
  { key: 'settings.live.default_temperature.help', en: 'Sampling temperature used when a request omits temperature.', ko: '요청에 temperature가 없을 때 사용하는 샘플링 온도입니다.', test_id: 'settings-live-default-temperature-help' },
  { key: 'settings.live.default_top_p', en: 'Top P', ko: 'Top P', test_id: 'settings-live-default-top-p' },
  { key: 'settings.live.default_top_p.help', en: 'Top-p sampling default, in (0, 1].', ko: '(0, 1] 범위의 Top-p 샘플링 기본값입니다.', test_id: 'settings-live-default-top-p-help' },
  { key: 'settings.live.default_top_k', en: 'Top K', ko: 'Top K', test_id: 'settings-live-default-top-k' },
  { key: 'settings.live.default_top_k.help', en: 'Top-k sampling default.', ko: 'Top-k 샘플링 기본값입니다.', test_id: 'settings-live-default-top-k-help' },
  { key: 'settings.live.default_min_p', en: 'Min P', ko: 'Min P', test_id: 'settings-live-default-min-p' },
  { key: 'settings.live.default_min_p.help', en: 'Min-p sampling default, in [0, 1].', ko: '[0, 1] 범위의 Min-p 샘플링 기본값입니다.', test_id: 'settings-live-default-min-p-help' },
  { key: 'settings.live.default_repetition_penalty', en: 'Repetition penalty', ko: '반복 페널티', test_id: 'settings-live-default-repetition-penalty' },
  { key: 'settings.live.default_repetition_penalty.help', en: 'Repetition penalty used when a request omits it.', ko: '요청에 없을 때 사용하는 반복 페널티입니다.', test_id: 'settings-live-default-repetition-penalty-help' },
  { key: 'settings.live.default_repetition_context_size', en: 'Repetition window', ko: '반복 검사 범위', test_id: 'settings-live-default-repetition-context-size' },
  { key: 'settings.live.default_repetition_context_size.help', en: 'Token history window that repetition penalties check.', ko: '반복 페널티가 검사하는 토큰 기록 범위입니다.', test_id: 'settings-live-default-repetition-context-size-help' },
  { key: 'settings.live.default_max_tokens', en: 'Max tokens', ko: '최대 토큰', test_id: 'settings-live-default-max-tokens' },
  { key: 'settings.live.default_max_tokens.help', en: 'Generation budget used when a request omits max_tokens.', ko: '요청에 max_tokens가 없을 때 사용하는 생성 한도입니다.', test_id: 'settings-live-default-max-tokens-help' },
  { key: 'settings.live.default_seed', en: 'Seed', ko: '시드', test_id: 'settings-live-default-seed' },
  { key: 'settings.live.default_seed.help', en: 'Seed used when a request omits one. Left unset, each request gets a random seed.', ko: '요청에 시드가 없을 때 사용하는 값입니다. 설정하지 않으면 요청마다 무작위 시드를 사용합니다.', test_id: 'settings-live-default-seed-help' },
  { key: 'settings.live.default_frequency_penalty', en: 'Frequency penalty', ko: '빈도 페널티', test_id: 'settings-live-default-frequency-penalty' },
  { key: 'settings.live.default_frequency_penalty.help', en: 'Frequency penalty used when a request omits it.', ko: '요청에 없을 때 사용하는 빈도 페널티입니다.', test_id: 'settings-live-default-frequency-penalty-help' },
  { key: 'settings.live.default_presence_penalty', en: 'Presence penalty', ko: '존재 페널티', test_id: 'settings-live-default-presence-penalty' },
  { key: 'settings.live.default_presence_penalty.help', en: 'Presence penalty used when a request omits it.', ko: '요청에 없을 때 사용하는 존재 페널티입니다.', test_id: 'settings-live-default-presence-penalty-help' },
  { key: 'settings.live.default_dry_multiplier', en: 'DRY multiplier', ko: 'DRY 배수', test_id: 'settings-live-default-dry-multiplier' },
  { key: 'settings.live.default_dry_multiplier.help', en: 'DRY repetition multiplier.', ko: 'DRY 반복 억제 배수입니다.', test_id: 'settings-live-default-dry-multiplier-help' },
  { key: 'settings.live.default_dry_base', en: 'DRY base', ko: 'DRY 밑', test_id: 'settings-live-default-dry-base' },
  { key: 'settings.live.default_dry_base.help', en: 'DRY exponential base.', ko: 'DRY 지수의 밑입니다.', test_id: 'settings-live-default-dry-base-help' },
  { key: 'settings.live.default_dry_allowed_length', en: 'DRY allowed length', ko: 'DRY 허용 길이', test_id: 'settings-live-default-dry-allowed-length' },
  { key: 'settings.live.default_dry_allowed_length.help', en: 'Repeat length DRY allows before penalizing.', ko: 'DRY가 페널티 없이 허용하는 반복 길이입니다.', test_id: 'settings-live-default-dry-allowed-length-help' },
  { key: 'settings.live.default_dry_penalty_last_n', en: 'DRY history window', ko: 'DRY 기록 범위', test_id: 'settings-live-default-dry-penalty-last-n' },
  { key: 'settings.live.default_dry_penalty_last_n.help', en: 'Token history window that DRY checks.', ko: 'DRY가 검사하는 토큰 기록 범위입니다.', test_id: 'settings-live-default-dry-penalty-last-n-help' },
  { key: 'settings.live.default_dry_sequence_breakers', en: 'DRY sequence breakers', ko: 'DRY 시퀀스 구분자', test_id: 'settings-live-default-dry-sequence-breakers' },
  { key: 'settings.live.default_dry_sequence_breakers.help', en: 'Strings that end a DRY repeat, as a JSON array.', ko: 'DRY 반복을 끊는 문자열 목록(JSON 배열)입니다.', test_id: 'settings-live-default-dry-sequence-breakers-help' },
  { key: 'settings.live.lang_bias_config', en: 'Language bias', ko: '언어 편향', test_id: 'settings-live-lang-bias-config' },
  { key: 'settings.live.lang_bias_config.help', en: 'Language-bias policy for newly admitted requests, as a JSON object.', ko: '새로 수락되는 요청에 적용되는 언어 편향 정책(JSON 객체)입니다.', test_id: 'settings-live-lang-bias-config-help' },
  { key: 'settings.live.reasoning_budget', en: 'Reasoning budget', ko: '추론 예산', test_id: 'settings-live-reasoning-budget' },
  { key: 'settings.live.reasoning_budget.help', en: '-1 is unbounded, 0 ends thinking immediately, and N caps reasoning tokens.', ko: '-1은 무제한, 0은 추론을 즉시 종료, N은 추론 토큰 상한입니다.', test_id: 'settings-live-reasoning-budget-help' },
  { key: 'settings.live.chat_template_kwargs', en: 'Chat template arguments', ko: '대화 템플릿 인수', test_id: 'settings-live-chat-template-kwargs' },
  { key: 'settings.live.chat_template_kwargs.help', en: 'Template arguments merged under each request\'s own, as a JSON object.', ko: '요청별 인수 아래에 병합되는 템플릿 인수(JSON 객체)입니다.', test_id: 'settings-live-chat-template-kwargs-help' },
  { key: 'settings.live.loop_detection', en: 'Loop detection', ko: '반복 루프 감지', test_id: 'settings-live-loop-detection' },
  { key: 'settings.live.loop_detection.help', en: 'Server-wide N-gram loop-detection override, as a JSON object.', ko: '서버 전체의 N-gram 반복 루프 감지 재정의(JSON 객체)입니다.', test_id: 'settings-live-loop-detection-help' },
  { key: 'settings.live.max_denoising_steps', en: 'Max denoising steps', ko: '최대 디노이징 단계', test_id: 'settings-live-max-denoising-steps' },
  { key: 'settings.live.max_denoising_steps.help', en: 'Optional cap on diffusion denoising steps.', ko: '디퓨전 디노이징 단계의 선택적 상한입니다.', test_id: 'settings-live-max-denoising-steps-help' },
  { key: 'settings.live.diffusion_sampler', en: 'Diffusion sampler', ko: '디퓨전 샘플러', test_id: 'settings-live-diffusion-sampler' },
  { key: 'settings.live.diffusion_sampler.help', en: 'Default sampler for diffusion generation.', ko: '디퓨전 생성의 기본 샘플러입니다.', test_id: 'settings-live-diffusion-sampler-help' },
  { key: 'settings.live.diffusion_threshold', en: 'Diffusion threshold', ko: '디퓨전 임계값', test_id: 'settings-live-diffusion-threshold' },
  { key: 'settings.live.diffusion_threshold.help', en: 'Confidence threshold for diffusion threshold sampling.', ko: '디퓨전 임계값 샘플링의 신뢰도 임계값입니다.', test_id: 'settings-live-diffusion-threshold-help' },
] as const;

/** Catalog keys that name a live setting (`settings.live.<name>`) or its help (`settings.live.<name>.help`). */
export const LIVE_SETTING_KEYS: ReadonlySet<string> = new Set(liveSettingStrings.map((entry) => entry.key));

export const settingsStrings = [...settingsBaseStrings, ...liveSettingStrings] as const;
