// Copyright 2025-2026 Lablup Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! SSE stream bridging across the prefill-decode boundary.
//!
//! When a request is processed by disaggregated nodes, the SSE stream seen
//! by the client must be seamless:
//!
//! 1. The **first token** comes from the prefill node (sampled after the
//!    prefill forward pass completes).
//! 2. **Subsequent tokens** come from the decode node.
//! 3. The `[DONE]` marker is sent after the decode node finishes.
//!
//! The [`StreamBridge`] manages this handoff, ensuring no gaps and no
//! duplicate tokens in the client-visible stream.
//!
//! # Architecture
//!
//! ```text
//! Client <── SSE ──┐
//!                   │
//!           ┌───────┴────────┐
//!           │  StreamBridge  │
//!           │                │
//!           │ Phase 1: first │
//!           │   token from   │
//!           │   prefill node │
//!           │                │
//!           │ Phase 2: rest  │
//!           │   tokens from  │
//!           │   decode node  │
//!           └────────────────┘
//! ```
//!
//! Used by: disaggregated serving pipeline, server routes

use std::fmt;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::time::{Duration, Instant};

use serde::{Deserialize, Serialize};

// ── Stream Phase ─────────────────────────────────────────────────────

/// Phase of an SSE stream in the disaggregated pipeline.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum StreamPhase {
    /// Waiting for the prefill node to produce the first token.
    WaitingForPrefill,
    /// First token received; waiting for decode node to start.
    HandoffToDecode,
    /// Decode node is actively streaming tokens.
    Decoding,
    /// Stream is complete (DONE marker sent or error).
    Complete,
}

impl fmt::Display for StreamPhase {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::WaitingForPrefill => write!(f, "waiting_for_prefill"),
            Self::HandoffToDecode => write!(f, "handoff_to_decode"),
            Self::Decoding => write!(f, "decoding"),
            Self::Complete => write!(f, "complete"),
        }
    }
}

// ── Token Event ──────────────────────────────────────────────────────

/// A token event in the bridged stream.
///
/// Carries enough metadata to detect gaps and reorder if needed.
#[derive(Debug, Clone)]
pub struct TokenEvent {
    /// The token ID.
    pub token_id: i32,

    /// Decoded text for this token (may be empty for partial UTF-8).
    pub text: String,

    /// Monotonically increasing sequence number (0-based, relative to
    /// the start of generation for this request).
    pub sequence_number: u64,

    /// Which node produced this token.
    pub source: TokenSource,

    /// Whether this is the final token in the sequence.
    pub is_final: bool,
}

/// Where a token originated in the disaggregated pipeline.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TokenSource {
    /// Token was sampled by the prefill node (always sequence_number 0).
    Prefill,
    /// Token was generated by the decode node.
    Decode,
    /// Token was generated locally in hybrid mode.
    Local,
}

impl fmt::Display for TokenSource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Prefill => write!(f, "prefill"),
            Self::Decode => write!(f, "decode"),
            Self::Local => write!(f, "local"),
        }
    }
}

// ── Stream Bridge ────────────────────────────────────────────────────

/// Manages seamless SSE streaming across the prefill-decode boundary.
///
/// # Invariants
///
/// - The first token (sequence_number = 0) must come from the prefill node.
/// - Subsequent tokens (sequence_number >= 1) come from the decode node.
/// - No token sequence number is skipped or duplicated.
/// - The `[DONE]` marker is sent exactly once, after the final token.
///
/// # Thread Safety
///
/// The bridge uses a Mutex to guard phase transitions and sequence
/// validation atomically, preventing TOCTOU races when multiple threads
/// submit tokens concurrently.
pub struct StreamBridge {
    /// Request identifier for logging and correlation.
    request_id: String,

    /// Current phase of the stream and the sequence number of the last
    /// emitted token. Guarded by the same Mutex to prevent TOCTOU races
    /// between phase checks and sequence validation in submit_decode_token.
    state: std::sync::Mutex<BridgeState>,

    /// Total tokens emitted to the client.
    tokens_emitted: AtomicU64,

    /// Whether the bridge has been finalized (DONE sent).
    is_finalized: AtomicBool,

    /// Timestamp when the bridge was created.
    created_at: Instant,

    /// Maximum time to wait for the handoff from prefill to decode.
    handoff_timeout: Duration,
}

/// Internal state protected by the bridge's Mutex.
struct BridgeState {
    /// Current phase of the stream.
    phase: StreamPhase,
    /// Sequence number of the last token emitted to the client.
    last_emitted_seq: u64,
    /// Timestamp when the first token was emitted.
    first_token_at: Option<Instant>,
    /// Timestamp when the handoff phase started (for timeout measurement).
    handoff_started_at: Option<Instant>,
}

impl fmt::Debug for StreamBridge {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("StreamBridge")
            .field("request_id", &self.request_id)
            .field("phase", &self.current_phase())
            .field(
                "tokens_emitted",
                &self.tokens_emitted.load(Ordering::Relaxed),
            )
            .field("is_finalized", &self.is_finalized.load(Ordering::Relaxed))
            .finish()
    }
}

impl StreamBridge {
    /// Create a new stream bridge for the given request.
    pub fn new(request_id: String, handoff_timeout: Duration) -> Self {
        Self {
            request_id,
            state: std::sync::Mutex::new(BridgeState {
                phase: StreamPhase::WaitingForPrefill,
                last_emitted_seq: 0,
                first_token_at: None,
                handoff_started_at: None,
            }),
            tokens_emitted: AtomicU64::new(0),
            is_finalized: AtomicBool::new(false),
            created_at: Instant::now(),
            handoff_timeout,
        }
    }

    /// Return the request ID.
    pub fn request_id(&self) -> &str {
        &self.request_id
    }

    /// Return the current stream phase.
    pub fn current_phase(&self) -> StreamPhase {
        self.state
            .lock()
            .expect("stream bridge state lock poisoned")
            .phase
    }

    /// Return the total number of tokens emitted to the client.
    pub fn tokens_emitted(&self) -> u64 {
        self.tokens_emitted.load(Ordering::Relaxed)
    }

    /// Return the time since the bridge was created.
    pub fn elapsed(&self) -> Duration {
        self.created_at.elapsed()
    }

    /// Return the time-to-first-token if the first token has been emitted.
    pub fn time_to_first_token(&self) -> Option<Duration> {
        let state = self
            .state
            .lock()
            .expect("stream bridge state lock poisoned");
        state
            .first_token_at
            .map(|t| t.duration_since(self.created_at))
    }

    /// Check if the bridge has been finalized.
    pub fn is_finalized(&self) -> bool {
        self.is_finalized.load(Ordering::Relaxed)
    }

    /// Submit the first token from the prefill node.
    ///
    /// Transitions the phase from `WaitingForPrefill` to `HandoffToDecode`.
    /// Returns an error if the bridge is not in the `WaitingForPrefill` phase.
    pub fn submit_first_token(&self, token: &TokenEvent) -> Result<(), StreamBridgeError> {
        let mut state = self
            .state
            .lock()
            .map_err(|_| StreamBridgeError::LockPoisoned)?;

        if state.phase != StreamPhase::WaitingForPrefill {
            return Err(StreamBridgeError::InvalidPhaseTransition {
                from: state.phase,
                expected: StreamPhase::WaitingForPrefill,
            });
        }

        if token.sequence_number != 0 {
            return Err(StreamBridgeError::SequenceGap {
                expected: 0,
                got: token.sequence_number,
            });
        }

        // Record first token time.
        let now = Instant::now();
        state.first_token_at = Some(now);
        state.last_emitted_seq = 0;
        state.handoff_started_at = Some(now);
        state.phase = StreamPhase::HandoffToDecode;

        // Update token counter outside the critical section is fine since
        // it is only used for monitoring, not for correctness.
        drop(state);
        self.tokens_emitted.fetch_add(1, Ordering::Relaxed);

        Ok(())
    }

    /// Signal that the decode node has started streaming.
    ///
    /// Transitions from `HandoffToDecode` to `Decoding`.
    pub fn start_decode_stream(&self) -> Result<(), StreamBridgeError> {
        let mut state = self
            .state
            .lock()
            .map_err(|_| StreamBridgeError::LockPoisoned)?;

        if state.phase != StreamPhase::HandoffToDecode {
            return Err(StreamBridgeError::InvalidPhaseTransition {
                from: state.phase,
                expected: StreamPhase::HandoffToDecode,
            });
        }

        state.phase = StreamPhase::Decoding;
        Ok(())
    }

    /// Submit a decode token from the decode node.
    ///
    /// Validates sequence number continuity. The phase check and sequence
    /// validation are performed under the same lock to prevent TOCTOU
    /// races when multiple threads submit tokens concurrently.
    pub fn submit_decode_token(&self, token: &TokenEvent) -> Result<(), StreamBridgeError> {
        let mut state = self
            .state
            .lock()
            .map_err(|_| StreamBridgeError::LockPoisoned)?;

        if state.phase != StreamPhase::Decoding {
            return Err(StreamBridgeError::InvalidPhaseTransition {
                from: state.phase,
                expected: StreamPhase::Decoding,
            });
        }

        let expected_seq = state.last_emitted_seq + 1;
        if token.sequence_number != expected_seq {
            return Err(StreamBridgeError::SequenceGap {
                expected: expected_seq,
                got: token.sequence_number,
            });
        }

        state.last_emitted_seq = token.sequence_number;
        drop(state);

        self.tokens_emitted.fetch_add(1, Ordering::Relaxed);

        Ok(())
    }

    /// Finalize the stream (send DONE marker).
    ///
    /// Can be called from any non-finalized state. Transitions to `Complete`.
    /// Returns `false` if already finalized.
    pub fn finalize(&self) -> bool {
        if self
            .is_finalized
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return false;
        }

        if let Ok(mut state) = self.state.lock() {
            state.phase = StreamPhase::Complete;
        }
        true
    }

    /// Check if the handoff from prefill to decode has timed out.
    ///
    /// Timeout is measured from when the phase entered `HandoffToDecode`
    /// (i.e., when the first token was received), not from bridge creation.
    /// This prevents long prefill times from eating into the handoff budget.
    pub fn is_handoff_timed_out(&self) -> bool {
        let state = self
            .state
            .lock()
            .expect("stream bridge state lock poisoned");
        if state.phase != StreamPhase::HandoffToDecode {
            return false;
        }
        match state.handoff_started_at {
            Some(started) => started.elapsed() > self.handoff_timeout,
            None => false,
        }
    }
}

// ── Errors ───────────────────────────────────────────────────────────

/// Errors that can occur during stream bridging.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum StreamBridgeError {
    /// Phase transition is invalid (e.g., submitting a decode token before
    /// the first token from prefill).
    InvalidPhaseTransition {
        from: StreamPhase,
        expected: StreamPhase,
    },
    /// Token sequence number gap detected.
    SequenceGap { expected: u64, got: u64 },
    /// Internal lock was poisoned.
    LockPoisoned,
}

impl fmt::Display for StreamBridgeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidPhaseTransition { from, expected } => {
                write!(
                    f,
                    "invalid stream phase transition: current={from}, expected={expected}"
                )
            }
            Self::SequenceGap { expected, got } => {
                write!(
                    f,
                    "token sequence gap: expected seq={expected}, got seq={got}"
                )
            }
            Self::LockPoisoned => write!(f, "stream bridge internal lock poisoned"),
        }
    }
}

impl std::error::Error for StreamBridgeError {}

#[cfg(test)]
#[path = "stream_bridge_tests.rs"]
mod tests;
