// Copyright 2026 Lablup Inc. Licensed under the Apache License, Version 2.0.
// Chat, transcript, next-turn parameter and local-history copy. Every entry is
// mirrored in tests/fixtures/webui/strings.json; resolve it with t(locale, key).
export const chatStrings = [
  { key: 'chat.intro', en: 'Memory-only by default. Changing the model affects the next turn, never the running request.', ko: '기본적으로 메모리에만 보관합니다. 모델을 바꾸면 다음 턴에만 적용되며 실행 중인 요청은 바뀌지 않습니다.', test_id: 'chat-intro' },
  { key: 'chat.new_conversation', en: 'New conversation', ko: '새 대화', test_id: 'chat-new-conversation' },
  { key: 'chat.conversation.default_title', en: 'New conversation', ko: '새 대화', test_id: 'chat-conversation-default-title' },
  { key: 'chat.list.label', en: 'Conversations', ko: '대화 목록', test_id: 'chat-list-label' },
  { key: 'chat.list.open', en: 'Show conversations', ko: '대화 목록 보기', test_id: 'chat-list-open' },
  { key: 'chat.list.empty.title', en: 'No conversations yet', ko: '아직 대화가 없습니다', test_id: 'chat-list-empty-title' },
  { key: 'chat.list.empty.body', en: 'Send a message to start one, or choose New conversation.', ko: '메시지를 보내 대화를 시작하거나 새 대화를 선택하세요.', test_id: 'chat-list-empty-body' },
  { key: 'chat.list.no_messages', en: 'No messages yet', ko: '아직 메시지 없음', test_id: 'chat-list-no-messages' },
  { key: 'chat.list.limit', en: 'Conversation limit reached (50). Delete or export older conversations first.', ko: '대화 개수 한도(50개)에 도달했습니다. 먼저 이전 대화를 삭제하거나 내보내세요.', test_id: 'chat-list-limit' },
  { key: 'chat.list.rename', en: 'Rename {title}', ko: '{title} 이름 바꾸기', test_id: 'chat-list-rename' },
  { key: 'chat.list.rename_field', en: 'New name for {title}', ko: '{title}의 새 이름', test_id: 'chat-list-rename-field' },
  { key: 'chat.list.delete', en: 'Delete {title}', ko: '{title} 삭제', test_id: 'chat-list-delete' },
  { key: 'chat.list.delete.confirm.title', en: 'Delete {title}?', ko: '{title} 대화를 삭제할까요?', test_id: 'chat-list-delete-confirm-title' },
  { key: 'chat.list.delete.confirm.body', en: 'The conversation and all of its turns are removed. Export your history first if you want to keep a copy.', ko: '대화와 모든 턴이 삭제됩니다. 사본을 남기려면 먼저 기록을 내보내세요.', test_id: 'chat-list-delete-confirm-body' },
  { key: 'chat.list.delete.confirm', en: 'Delete conversation', ko: '대화 삭제', test_id: 'chat-list-delete-confirm' },
  { key: 'chat.model.label', en: 'Model for next turn', ko: '다음 턴에 사용할 모델', test_id: 'chat-model-label' },
  { key: 'chat.model.choose', en: 'Select a model', ko: '모델 선택', test_id: 'chat-model-choose' },
  { key: 'chat.model.group.ready', en: 'Ready to chat', ko: '대화 준비됨', test_id: 'chat-model-group-ready' },
  { key: 'chat.model.group.unloaded', en: 'Not loaded', ko: '로드되지 않음', test_id: 'chat-model-group-unloaded' },
  { key: 'chat.model.group.failed', en: 'Load failed', ko: '로드 실패', test_id: 'chat-model-group-failed' },
  { key: 'chat.model.group.unavailable', en: 'Not available for chat', ko: '대화에 사용할 수 없음', test_id: 'chat-model-group-unavailable' },
  { key: 'chat.model.hint.choose', en: 'Choose a model to start.', ko: '시작하려면 모델을 선택하세요.', test_id: 'chat-model-hint-choose' },
  { key: 'chat.model.hint.load', en: 'Not loaded. Load it to chat; selecting a model never loads it.', ko: '로드되지 않았습니다. 대화하려면 로드하세요. 모델을 선택하는 것만으로는 로드하지 않습니다.', test_id: 'chat-model-hint-load' },
  { key: 'chat.model.hint.cannot_load', en: 'This model cannot be loaded from here. Open Models for the reason.', ko: '여기에서는 이 모델을 로드할 수 없습니다. 모델 화면에서 이유를 확인하세요.', test_id: 'chat-model-hint-cannot-load' },
  { key: 'chat.model.hint.wait', en: 'Not ready yet. Send turns on once the model is ready to chat.', ko: '아직 준비되지 않았습니다. 모델이 대화 준비를 마치면 보내기가 켜집니다.', test_id: 'chat-model-hint-wait' },
  { key: 'chat.model.hint.unavailable', en: 'This model does not offer chat. Embeddings, reranking and other tasks use their documented API, not this composer.', ko: '이 모델은 대화를 지원하지 않습니다. 임베딩, 재순위화 등 다른 작업은 이 입력창이 아니라 문서화된 API를 사용합니다.', test_id: 'chat-model-hint-unavailable' },
  { key: 'chat.load.confirm.title', en: 'Load {model}?', ko: '{model} 모델을 로드할까요?', test_id: 'chat-load-confirm-title' },
  { key: 'chat.load.confirm.body', en: 'Selecting a model never loads it. Loading starts a server operation that reserves memory for this model and keeps running if you leave Chat.', ko: '모델을 선택하는 것만으로는 로드하지 않습니다. 로드는 이 모델에 메모리를 예약하는 서버 작업을 시작하며, 대화 화면을 떠나도 계속 진행됩니다.', test_id: 'chat-load-confirm-body' },
  { key: 'chat.load.requested', en: 'Load requested. Send turns on when the model is ready.', ko: '로드를 요청했습니다. 모델이 준비되면 보내기가 켜집니다.', test_id: 'chat-load-requested' },
  { key: 'chat.no_model.action', en: 'Open Models', ko: '모델 화면 열기', test_id: 'chat-no-model-action' },
  { key: 'chat.settings.summary', en: 'Conversation settings', ko: '대화 설정', test_id: 'chat-settings-summary' },
  { key: 'chat.settings.name', en: 'Conversation name', ko: '대화 이름', test_id: 'chat-settings-name' },
  { key: 'chat.settings.system_prompt', en: 'System prompt', ko: '시스템 프롬프트', test_id: 'chat-settings-system-prompt' },
  { key: 'chat.settings.sampling', en: 'Sampling defaults are set in {link} and frozen when sending.', ko: '샘플링 기본값은 {link}에서 지정하며 전송할 때 고정됩니다.', test_id: 'chat-settings-sampling' },
  { key: 'chat.settings.title', en: 'Chat settings', ko: '대화 화면 설정', test_id: 'chat-settings-title' },
  { key: 'chat.settings.none', en: 'Start or select a conversation to name it and set its system prompt.', ko: '대화를 시작하거나 선택하면 이름과 시스템 프롬프트를 지정할 수 있습니다.', test_id: 'chat-settings-none' },
  { key: 'chat.overrides', en: 'Overrides: {keys}', ko: '재정의: {keys}', test_id: 'chat-overrides' },
  { key: 'chat.composer.label', en: 'Message', ko: '메시지', test_id: 'chat-composer-label' },
  { key: 'chat.composer.hint', en: 'Enter sends · Shift+Enter inserts a line · Cmd/Ctrl+Enter also sends.', ko: 'Enter로 보내고 Shift+Enter로 줄을 바꿉니다. Cmd/Ctrl+Enter로도 보낼 수 있습니다.', test_id: 'chat-composer-hint' },
  { key: 'chat.composer.count', en: '{count} / {max}', ko: '{count} / {max}자', test_id: 'chat-composer-count' },
  { key: 'chat.composer.limit', en: 'Limit reached', ko: '한도 도달', test_id: 'chat-composer-limit' },
  { key: 'chat.composer.keys', en: 'Keyboard hints', ko: '키보드 도움말', test_id: 'chat-composer-keys' },
  { key: 'chat.images.attach', en: 'Attach images', ko: '이미지 첨부', test_id: 'chat-images-attach' },
  { key: 'chat.images.label', en: 'Local images', ko: '로컬 이미지', test_id: 'chat-images-label' },
  { key: 'chat.images.remove', en: 'Remove {name}', ko: '{name} 제거', test_id: 'chat-images-remove' },
  { key: 'chat.stop', en: 'Stop', ko: '중지', test_id: 'chat-stop' },
  { key: 'chat.error.title', en: 'Chat could not continue', ko: '대화를 계속할 수 없습니다', test_id: 'chat-error-title' },
  { key: 'chat.error.view_closed', en: 'View closed. The request was aborted and was not retried.', ko: '화면을 닫았습니다. 요청을 중단했으며 다시 시도하지 않았습니다.', test_id: 'chat-error-view-closed' },
  { key: 'chat.error.vision_unsupported', en: 'The selected provider does not confirm vision support. Remove images or select a vision model.', ko: '선택한 provider가 비전 지원을 확인하지 않습니다. 이미지를 제거하거나 비전 모델을 선택하세요.', test_id: 'chat-error-vision-unsupported' },
  { key: 'chat.error.conversation_limit', en: 'Conversation limit reached. Delete or export older conversations first.', ko: '대화 개수 한도에 도달했습니다. 먼저 이전 대화를 삭제하거나 내보내세요.', test_id: 'chat-error-conversation-limit' },
  { key: 'chat.error.invalid_parameters', en: 'Invalid next-turn parameters.', ko: '다음 턴 매개변수가 올바르지 않습니다.', test_id: 'chat-error-invalid-parameters' },
  { key: 'chat.error.turn_limit', en: 'This conversation reached its 100-turn limit. Start a new conversation.', ko: '이 대화는 100턴 한도에 도달했습니다. 새 대화를 시작하세요.', test_id: 'chat-error-turn-limit' },
  { key: 'chat.error.images_exceed', en: 'Conversation images exceed the current server count, size or decode limits. Remove attachments or start a new conversation.', ko: '대화 이미지가 현재 서버의 개수, 크기 또는 디코드 한도를 넘습니다. 첨부를 제거하거나 새 대화를 시작하세요.', test_id: 'chat-error-images-exceed' },
  { key: 'chat.error.body_limit', en: 'The complete request exceeds the server or 16 MiB browser JSON body limit. Remove attachments or start a shorter conversation.', ko: '전체 요청이 서버 또는 16 MiB 브라우저 JSON 본문 한도를 넘습니다. 첨부를 제거하거나 더 짧은 대화를 시작하세요.', test_id: 'chat-error-body-limit' },
  { key: 'chat.error.memory_budget', en: 'Conversation memory budget reached. Export and clear older history first.', ko: '대화 메모리 예산에 도달했습니다. 먼저 이전 기록을 내보내고 지우세요.', test_id: 'chat-error-memory-budget' },
  { key: 'chat.error.memory_budget_stream', en: 'Conversation memory budget reached. No further output was retained.', ko: '대화 메모리 예산에 도달했습니다. 이후 출력은 보존하지 않았습니다.', test_id: 'chat-error-memory-budget-stream' },
  { key: 'chat.error.generation_failed', en: 'Generation failed or disconnected. Partial output is preserved. Check context limits, authentication and server availability; nothing was retried.', ko: '생성에 실패했거나 연결이 끊겼습니다. 부분 출력은 보존됩니다. 컨텍스트 한도, 인증, 서버 상태를 확인하세요. 자동으로 다시 시도하지 않았습니다.', test_id: 'chat-error-generation-failed' },
  { key: 'chat.error.images_invalid', en: 'Images must be bounded local PNG, JPEG or WebP files. No URL, SVG or HTML input is accepted.', ko: '이미지는 크기 한도 안의 로컬 PNG, JPEG 또는 WebP 파일이어야 합니다. URL, SVG, HTML 입력은 허용하지 않습니다.', test_id: 'chat-error-images-invalid' },
  { key: 'chat.announce.stopped', en: 'Stopped locally; checking server activity.', ko: '로컬에서 중지했습니다. 서버 활동을 확인하는 중입니다.', test_id: 'chat-announce-stopped' },
  { key: 'chat.announce.aborted_observed', en: 'Request aborted. Server observation refreshed at {time}. See Activity for active requests; this is not a per-request cancellation receipt.', ko: '요청을 중단했습니다. 서버 관측값을 {time}에 새로 고쳤습니다. 활성 요청은 활동 화면에서 확인하세요. 이 메시지는 요청별 취소 확인이 아닙니다.', test_id: 'chat-announce-aborted-observed' },
  { key: 'chat.announce.unknown_time', en: 'an unknown time', ko: '알 수 없는 시각', test_id: 'chat-announce-unknown-time' },
  { key: 'chat.announce.aborted_unobserved', en: 'Request aborted. Backend cancellation could not be observed; inspect Activity before unloading.', ko: '요청을 중단했습니다. 백엔드 취소를 확인할 수 없으니 언로드하기 전에 활동 화면을 확인하세요.', test_id: 'chat-announce-aborted-unobserved' },
  { key: 'chat.announce.generating', en: 'Generating.', ko: '생성하는 중입니다.', test_id: 'chat-announce-generating' },
  { key: 'chat.announce.complete', en: 'Response finished.', ko: '응답이 끝났습니다.', test_id: 'chat-announce-complete' },
  { key: 'chat.announce.failed', en: 'Generation failed; partial response preserved.', ko: '생성에 실패했습니다. 부분 응답은 보존됩니다.', test_id: 'chat-announce-failed' },
  { key: 'chat.transcript.label', en: 'Conversation transcript', ko: '대화 기록', test_id: 'chat-transcript-label' },
  { key: 'chat.transcript.empty', en: 'No messages yet. Start with a prompt after loading a model.', ko: '아직 메시지가 없습니다. 모델을 로드한 뒤 프롬프트를 입력해 시작하세요.', test_id: 'chat-transcript-empty' },
  { key: 'chat.transcript.jump', en: 'Jump to latest', ko: '최신 메시지로 이동', test_id: 'chat-transcript-jump' },
  { key: 'chat.transcript.turn_label', en: 'Turn with {model}', ko: '{model} 턴', test_id: 'chat-transcript-turn-label' },
  { key: 'chat.message.you', en: 'You', ko: '나', test_id: 'chat-message-you' },
  { key: 'chat.message.prompt_actions', en: 'Prompt actions', ko: '프롬프트 작업', test_id: 'chat-message-prompt-actions' },
  { key: 'chat.message.response_actions', en: 'Response actions', ko: '응답 작업', test_id: 'chat-message-response-actions' },
  { key: 'chat.message.elapsed', en: '{status} · {seconds} s', ko: '{status} · {seconds}초', test_id: 'chat-message-elapsed' },
  { key: 'chat.message.copy_prompt', en: 'Copy prompt', ko: '프롬프트 복사', test_id: 'chat-message-copy-prompt' },
  { key: 'chat.message.copied_prompt', en: 'Copied prompt.', ko: '프롬프트를 복사했습니다.', test_id: 'chat-message-copied-prompt' },
  { key: 'chat.message.copy_prompt_failed', en: 'Copy unavailable; select the prompt text instead.', ko: '복사할 수 없습니다. 프롬프트 텍스트를 직접 선택하세요.', test_id: 'chat-message-copy-prompt-failed' },
  { key: 'chat.message.retry', en: 'Retry response', ko: '응답 다시 시도', test_id: 'chat-message-retry' },
  { key: 'chat.message.not_executed', en: 'Not executed', ko: '실행하지 않음', test_id: 'chat-message-not-executed' },
  { key: 'chat.transcript.status.streaming', en: 'Generating', ko: '생성 중', test_id: 'chat-transcript-status-streaming' },
  { key: 'chat.transcript.status.complete', en: 'Done', ko: '완료', test_id: 'chat-transcript-status-complete' },
  { key: 'chat.transcript.status.cancelled', en: 'Stopped', ko: '중지됨', test_id: 'chat-transcript-status-cancelled' },
  { key: 'chat.transcript.status.interrupted', en: 'Did not finish', ko: '완료되지 않음', test_id: 'chat-transcript-status-interrupted' },
  { key: 'chat.transcript.status.error', en: 'Failed', ko: '실패', test_id: 'chat-transcript-status-error' },
  { key: 'chat.transcript.images', en: '{count} local image attachment(s)', ko: '로컬 이미지 첨부 {count}개', test_id: 'chat-transcript-images' },
  { key: 'chat.transcript.edit', en: 'Edit and regenerate', ko: '편집 후 다시 생성', test_id: 'chat-transcript-edit' },
  { key: 'chat.transcript.edit.confirm.title', en: 'Edit this prompt?', ko: '이 프롬프트를 편집할까요?', test_id: 'chat-transcript-edit-confirm-title' },
  { key: 'chat.transcript.edit.confirm.body', en: 'This response and all later turns in this conversation are discarded. The prompt returns to the composer.', ko: '이 응답과 이 대화의 이후 모든 턴이 삭제됩니다. 프롬프트는 입력창으로 돌아갑니다.', test_id: 'chat-transcript-edit-confirm-body' },
  { key: 'chat.transcript.edit.confirm', en: 'Discard and edit', ko: '삭제하고 편집', test_id: 'chat-transcript-edit-confirm' },
  { key: 'chat.transcript.reasoning_thinking', en: 'Reasoning · Thinking', ko: '추론 · 생각하는 중', test_id: 'chat-transcript-reasoning-thinking' },
  { key: 'chat.transcript.thinking', en: 'Thinking…', ko: '생각하는 중…', test_id: 'chat-transcript-thinking' },
  { key: 'chat.transcript.waiting', en: 'Waiting for response…', ko: '응답을 기다리는 중…', test_id: 'chat-transcript-waiting' },
  { key: 'chat.transcript.tool_call', en: 'Tool call: {name} (not executed)', ko: '도구 호출: {name} (실행하지 않음)', test_id: 'chat-transcript-tool-call' },
  { key: 'chat.transcript.tool_name_pending', en: 'Name pending', ko: '이름 대기 중', test_id: 'chat-transcript-tool-name-pending' },
  { key: 'chat.transcript.copy', en: 'Copy response', ko: '응답 복사', test_id: 'chat-transcript-copy' },
  { key: 'chat.transcript.copied', en: 'Copied response.', ko: '응답을 복사했습니다.', test_id: 'chat-transcript-copied' },
  { key: 'chat.transcript.copy_failed', en: 'Copy unavailable; select the response text instead.', ko: '복사할 수 없습니다. 응답 텍스트를 직접 선택하세요.', test_id: 'chat-transcript-copy-failed' },
  { key: 'chat.transcript.details', en: 'Response details', ko: '응답 상세', test_id: 'chat-transcript-details' },
  { key: 'chat.transcript.finish_reason', en: 'Finish reason', ko: '종료 사유', test_id: 'chat-transcript-finish-reason' },
  { key: 'chat.transcript.unknown', en: 'Unknown', ko: '알 수 없음', test_id: 'chat-transcript-unknown' },
  { key: 'chat.transcript.usage', en: 'Usage (server reported)', ko: '사용량 (서버 보고)', test_id: 'chat-transcript-usage' },
  { key: 'chat.transcript.usage_value', en: '{prompt} prompt / {completion} completion / {total} total tokens', ko: '프롬프트 {prompt} / 완성 {completion} / 전체 {total} 토큰', test_id: 'chat-transcript-usage-value' },
  { key: 'chat.transcript.first_delta', en: 'First delta (client observed)', ko: '첫 델타 (클라이언트 관측)', test_id: 'chat-transcript-first-delta' },
  { key: 'chat.transcript.decode_rate', en: 'Decode rate (client estimate)', ko: '디코드 속도 (클라이언트 추정)', test_id: 'chat-transcript-decode-rate' },
  { key: 'chat.transcript.metrics_note', en: 'First delta measures send to first non-empty content, reasoning or tool delta, including transport. Decode rate uses reported completion tokens minus one over the remaining client-observed stream duration; it is not a server kernel metric.', ko: '첫 델타는 전송부터 비어 있지 않은 첫 내용, 추론 또는 도구 델타까지의 시간이며 전송 구간을 포함합니다. 디코드 속도는 보고된 완성 토큰 수에서 1을 뺀 값을 클라이언트가 관측한 나머지 스트림 시간으로 나눈 값이며 서버 커널 지표가 아닙니다.', test_id: 'chat-transcript-metrics-note' },
  { key: 'chat.params.summary', en: 'Parameters for next turn', ko: '다음 턴 매개변수', test_id: 'chat-params-summary' },
  { key: 'chat.params.body', en: 'These overrides apply once, after Send accepts a request. Blank fields inherit Settings; absent Settings fields inherit the server. Changes never affect a running turn.', ko: '이 재정의 값은 보내기로 요청이 수락된 뒤 한 번만 적용됩니다. 빈 필드는 설정 값을, 설정에 없는 필드는 서버 값을 상속합니다. 실행 중인 턴에는 영향을 주지 않습니다.', test_id: 'chat-params-body' },
  { key: 'chat.params.field', en: 'Next turn {name}', ko: '다음 턴 {name}', test_id: 'chat-params-field' },
  { key: 'chat.params.inherited', en: 'Inherited: {value}', ko: '상속 값: {value}', test_id: 'chat-params-inherited' },
  { key: 'chat.params.server_default', en: 'server default', ko: '서버 기본값', test_id: 'chat-params-server-default' },
  { key: 'chat.params.clear', en: 'Clear next-turn overrides', ko: '다음 턴 재정의 지우기', test_id: 'chat-params-clear' },
  { key: 'chat.privacy.summary', en: 'Local history and privacy', ko: '로컬 기록과 개인정보', test_id: 'chat-privacy-summary' },
  { key: 'chat.privacy.body', en: 'Conversations stay in memory unless you opt in below. Signing out or refreshing requires authentication again; saved history belongs to this browser origin, not a server account. No API keys are stored.', ko: '아래에서 동의하지 않으면 대화는 메모리에만 남습니다. 로그아웃하거나 새로고침하면 다시 인증해야 합니다. 저장된 기록은 서버 계정이 아니라 이 브라우저 origin에 속합니다. API 키는 저장하지 않습니다.', test_id: 'chat-privacy-body' },
  { key: 'chat.privacy.save', en: 'Save conversations on this device (IndexedDB)', ko: '이 기기에 대화 저장 (IndexedDB)', test_id: 'chat-privacy-save' },
  { key: 'chat.privacy.include_images', en: 'Also include attached image bytes in saved history and exports (separate consent)', ko: '저장 기록과 내보내기에 첨부 이미지 바이트도 포함 (별도 동의)', test_id: 'chat-privacy-include-images' },
  { key: 'chat.privacy.note', en: 'Turning saving off stops future writes; use Clear All to remove previously saved history. Re-enable explicitly after refresh to read it.', ko: '저장을 끄면 이후 쓰기만 멈춥니다. 이미 저장된 기록은 모두 지우기로 삭제하세요. 새로고침 후 기록을 읽으려면 다시 명시적으로 켜세요.', test_id: 'chat-privacy-note' },
  { key: 'chat.privacy.export', en: 'Export JSON', ko: 'JSON 내보내기', test_id: 'chat-privacy-export' },
  { key: 'chat.privacy.export_failed', en: 'Export exceeds the bounded history size or contains unsupported data.', ko: '내보내기가 기록 크기 한도를 넘거나 지원하지 않는 데이터를 포함합니다.', test_id: 'chat-privacy-export-failed' },
  { key: 'chat.privacy.clear', en: 'Clear All', ko: '모두 지우기', test_id: 'chat-privacy-clear' },
  { key: 'chat.privacy.cleared', en: 'All history cleared.', ko: '모든 기록을 지웠습니다.', test_id: 'chat-privacy-cleared' },
  { key: 'chat.privacy.clear_failed', en: 'Stored history could not be cleared. Check browser storage permissions; no success is claimed.', ko: '저장된 기록을 지우지 못했습니다. 브라우저 저장소 권한을 확인하세요. 성공으로 처리하지 않았습니다.', test_id: 'chat-privacy-clear-failed' },
  { key: 'chat.privacy.import', en: 'Import conversation JSON (replaces current history)', ko: '대화 JSON 가져오기 (현재 기록을 대체)', test_id: 'chat-privacy-import' },
  { key: 'chat.privacy.import_too_large', en: 'Import exceeds 16 MiB.', ko: '가져오기가 16 MiB를 넘습니다.', test_id: 'chat-privacy-import-too-large' },
  { key: 'chat.privacy.import_rejected', en: 'Import rejected: unsupported version, invalid data or exceeded limits.', ko: '가져오기를 거부했습니다. 지원하지 않는 버전, 잘못된 데이터 또는 한도 초과입니다.', test_id: 'chat-privacy-import-rejected' },
  { key: 'chat.privacy.save_failed', en: 'History was not saved. Storage may be full or unavailable; export your conversation.', ko: '기록을 저장하지 못했습니다. 저장소가 가득 찼거나 사용할 수 없을 수 있으니 대화를 내보내세요.', test_id: 'chat-privacy-save-failed' },
  { key: 'chat.privacy.open_failed', en: 'Local history could not be opened or its images failed validation. Nothing was saved.', ko: '로컬 기록을 열 수 없거나 이미지 검증에 실패했습니다. 아무것도 저장하지 않았습니다.', test_id: 'chat-privacy-open-failed' },
  { key: 'chat.privacy.title', en: 'Local history', ko: '로컬 기록', test_id: 'chat-privacy-title' },
  { key: 'chat.privacy.replace_saved.confirm.title', en: 'Replace the in-memory conversations with saved history?', ko: '메모리의 대화를 저장된 기록으로 바꿀까요?', test_id: 'chat-privacy-replace-saved-confirm-title' },
  { key: 'chat.privacy.replace_saved.confirm.body', en: 'The conversations in memory are discarded and replaced by the saved history. Export current conversations first if needed.', ko: '메모리의 대화는 삭제되고 저장된 기록으로 대체됩니다. 필요하면 먼저 현재 대화를 내보내세요.', test_id: 'chat-privacy-replace-saved-confirm-body' },
  { key: 'chat.privacy.replace_saved.confirm', en: 'Replace with saved history', ko: '저장된 기록으로 바꾸기', test_id: 'chat-privacy-replace-saved-confirm' },
  { key: 'chat.privacy.clear.confirm.title', en: 'Delete all in-memory and saved conversations for this browser origin?', ko: '이 브라우저 origin의 메모리 대화와 저장된 대화를 모두 삭제할까요?', test_id: 'chat-privacy-clear-confirm-title' },
  { key: 'chat.privacy.clear.confirm', en: 'Delete all history', ko: '모든 기록 삭제', test_id: 'chat-privacy-clear-confirm' },
  { key: 'chat.privacy.replace_import.confirm.title', en: 'Replace the current conversations with validated imported history?', ko: '현재 대화를 검증된 가져온 기록으로 바꿀까요?', test_id: 'chat-privacy-replace-import-confirm-title' },
  { key: 'chat.privacy.replace_import.confirm.body', en: 'The current conversations are discarded and replaced by the imported history. Export current conversations first if needed.', ko: '현재 대화는 삭제되고 가져온 기록으로 대체됩니다. 필요하면 먼저 현재 대화를 내보내세요.', test_id: 'chat-privacy-replace-import-confirm-body' },
  { key: 'chat.privacy.replace_import.confirm', en: 'Replace with imported history', ko: '가져온 기록으로 바꾸기', test_id: 'chat-privacy-replace-import-confirm' },
] as const;
