// Copyright 2025-2026 Lablup Inc. and Jeongkyu Shin
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Portions of this file are derived from mlx-vlm
// (https://github.com/Blaizzy/mlx-vlm), Copyright 2025 Prince Canuma,
// licensed under the MIT License. See the top-level NOTICE file for the
// attribution carried forward under the MIT License.

//! Qwen3-Omni speech-output pipeline (stage 2): thinker text -> talker codec
//! frames -> code2wav waveform.
//!
//! Non-streaming two-pass design: after normal thinker text generation
//! completes, the full token sequence (prompt + generated answer) is
//! re-embedded and segmented at `<|im_start|>` boundaries exactly like the
//! reference. For text tokens the talker consumes the thinker's *token
//! embeddings* through `text_projection` (per the reference, the thinker's
//! transformer hidden states are only consumed at multimodal positions
//! through `hidden_projection`), so a text-only prompt needs no extra thinker
//! forward pass at all. Multimodal-conditioned speech (which would tap layer
//! `accept_hidden_layer` via
//! [`crate::models::Qwen3VLMoeModel::forward_hidden_states`]) is not wired
//! yet; prompts containing image/video/audio placeholders are rejected.
//!
//! Reference: mlx-vlm
//! <https://github.com/Blaizzy/mlx-vlm/blob/main/mlx_vlm/models/qwen3_omni_moe/qwen3_omni_moe.py>
//! (`Model.generate`, `_get_talker_user_parts`, `_get_talker_assistant_parts`).
//!
//! Used by: `mlxcel generate --output-audio` (CLI speech path).

use mlxcel_core::{MlxArray, UniquePtr};

use super::code2wav::Code2WavModel;
use super::speech_config::{Qwen3OmniSpeechConfig, SPEECH_SAMPLE_RATE};
use super::talker::Talker;
use crate::vision::qwen3_omni_moe::Qwen3OmniMoeModel;

/// Synthesized speech for one generated answer.
pub struct SpeechOutput {
    /// Mono samples in `[-1, 1]` at [`SpeechOutput::sample_rate`].
    pub samples: Vec<f32>,
    /// Codec frames generated by the talker (80 ms each).
    pub frames: usize,
    pub sample_rate: u32,
}

/// The lazily-loaded speech stack (talker + code2wav + config). Kept separate
/// from [`Qwen3OmniMoeModel`] so the default text/vision path pays zero extra
/// memory; the CLI loads this bundle only when `--output-audio` is passed.
pub struct Qwen3OmniSpeech {
    pub talker: Talker,
    pub code2wav: Code2WavModel,
    pub cfg: Qwen3OmniSpeechConfig,
}

/// `(start, end)` index pairs of `<|im_start|>`-delimited segments. Segment
/// starts come from the PROMPT tokens only (the reference scans `input_ids`);
/// the final segment extends to `full_len` (prompt + generated answer), so
/// the last assistant segment covers the generated text.
fn role_segments(prompt_tokens: &[i32], full_len: usize, im_start_id: i32) -> Vec<(usize, usize)> {
    let starts: Vec<usize> = prompt_tokens
        .iter()
        .enumerate()
        .filter_map(|(i, &t)| (t == im_start_id).then_some(i))
        .collect();
    starts
        .iter()
        .enumerate()
        .map(|(i, &s)| {
            let end = starts.get(i + 1).copied().unwrap_or(full_len);
            (s, end)
        })
        .collect()
}

impl Qwen3OmniSpeech {
    /// Build from a `WeightMap` restricted to the `talker.*` / `code2wav.*`
    /// prefixes (see `load_qwen3_omni_speech` in `src/loading/vlm_qwen.rs`).
    pub fn from_weights(
        weights: &mlxcel_core::weights::WeightMap,
        cfg: Qwen3OmniSpeechConfig,
    ) -> Result<Self, String> {
        let talker =
            Talker::from_weights(weights, &cfg.talker, "talker", cfg.group_size, cfg.bits)?;
        let code2wav = Code2WavModel::from_weights(
            weights,
            &cfg.code2wav,
            "code2wav",
            cfg.group_size,
            cfg.bits,
        )?;
        Ok(Self {
            talker,
            code2wav,
            cfg,
        })
    }

    /// Resolve a speaker name (case-insensitive) to its codec speaker id.
    fn speaker_id(&self, speaker: &str) -> Result<i32, String> {
        let key = speaker.to_lowercase();
        self.cfg
            .talker
            .speaker_id
            .get(&key)
            .copied()
            .ok_or_else(|| {
                let mut names: Vec<&str> = self
                    .cfg
                    .talker
                    .speaker_id
                    .keys()
                    .map(String::as_str)
                    .collect();
                names.sort_unstable();
                format!(
                    "Unknown speaker '{speaker}' (available: {})",
                    names.join(", ")
                )
            })
    }

    /// Synthesize speech for a completed generation. `prompt_tokens` is the
    /// chat-templated prompt; `generated_tokens` is the thinker's answer
    /// (normally ending in `<|im_end|>`). Text-only prompts only.
    pub fn synthesize(
        &self,
        omni: &Qwen3OmniMoeModel,
        prompt_tokens: &[i32],
        generated_tokens: &[i32],
        speaker: &str,
        max_frames: Option<usize>,
    ) -> Result<SpeechOutput, String> {
        let ids = &self.cfg.ids;
        let speaker_id = self.speaker_id(speaker)?;

        let mut full: Vec<i32> = Vec::with_capacity(prompt_tokens.len() + generated_tokens.len());
        full.extend_from_slice(prompt_tokens);
        full.extend_from_slice(generated_tokens);

        if full.iter().any(|t| ids.multimodal_token_ids.contains(t)) {
            return Err(
                "Speech output currently supports text-only prompts; image/video/audio inputs \
                 require the multimodal hidden-state conditioning path, which is not wired yet"
                    .to_string(),
            );
        }

        let segments = role_segments(prompt_tokens, full.len(), ids.im_start_token_id);
        if segments.is_empty() {
            return Err(
                "Speech output requires the chat-templated prompt (no <|im_start|> tokens found; \
                 do not combine --output-audio with --no-chat-template)"
                    .to_string(),
            );
        }

        // Project the tts control-token embeddings into the talker space.
        let specials = mlxcel_core::from_slice_i32(
            &[
                ids.tts_bos_token_id,
                ids.tts_eos_token_id,
                ids.tts_pad_token_id,
            ],
            &[1, 3],
        );
        let specials = omni.text_model.get_embed_tokens(&specials);
        let specials = self.talker.text_projection.forward(&specials);
        let hidden = mlxcel_core::array_shape(&specials)[2];
        let pick = |i: i32| mlxcel_core::slice(&specials, &[0, i, 0], &[1, i + 1, hidden]);
        let tts_bos_embed = pick(0);
        let tts_eos_embed = pick(1);
        let tts_pad_embed = pick(2);

        // Thinker token embeddings for a segment, projected into the talker
        // space (all positions are text tokens on this path).
        let project_segment = |seg: &[i32]| -> UniquePtr<MlxArray> {
            let arr = mlxcel_core::from_slice_i32(seg, &[1, seg.len() as i32]);
            let embeds = omni.text_model.get_embed_tokens(&arr);
            self.talker.text_projection.forward(&embeds)
        };

        let embed_dtype = mlxcel_core::array_dtype(&tts_pad_embed);
        let mut parts: Vec<UniquePtr<MlxArray>> = Vec::new();
        let mut trailing_text_hidden: Option<UniquePtr<MlxArray>> = None;

        for (i, &(start, end)) in segments.iter().enumerate() {
            let is_last = i + 1 == segments.len();
            let role = *full
                .get(start + 1)
                .ok_or_else(|| "Truncated <|im_start|> segment in prompt".to_string())?;

            if role == ids.system_token_id {
                continue;
            } else if role == ids.user_token_id {
                parts.push(project_segment(&full[start..end]));
            } else if role == ids.assistant_token_id {
                if !is_last {
                    continue;
                }
                // Reference `_get_talker_assistant_parts`: 3 header tokens
                // (<|im_start|>, assistant, newline), 4 x tts_pad, tts_bos,
                // then the first answer token; the codec side is 3 zeros then
                // [nothink, think_bos, think_eos, speaker, codec_pad,
                // codec_bos]. The remaining answer tokens (+ tts_eos) become
                // the trailing text stream fed one embedding per frame.
                let seg = &full[start..end];
                if seg.len() < 4 {
                    return Err(format!(
                        "Assistant segment too short for speech synthesis ({} tokens; \
                         did generation produce any answer tokens?)",
                        seg.len()
                    ));
                }
                let ah = project_segment(seg);
                let n = mlxcel_core::array_shape(&ah)[1];

                let header = mlxcel_core::slice(&ah, &[0, 0, 0], &[1, 3, hidden]);
                let pads = mlxcel_core::broadcast_to(&tts_pad_embed, &[1, 4, hidden]);
                let first_answer = mlxcel_core::slice(&ah, &[0, 3, 0], &[1, 4, hidden]);
                let text_hidden = mlxcel_core::concatenate(&header, &pads, 1);
                let text_hidden = mlxcel_core::concatenate(&text_hidden, &tts_bos_embed, 1);
                let text_hidden = mlxcel_core::concatenate(&text_hidden, &first_answer, 1);

                let tk = &self.cfg.talker;
                let codec_ids = mlxcel_core::from_slice_i32(
                    &[
                        tk.codec_nothink_id,
                        tk.codec_think_bos_id,
                        tk.codec_think_eos_id,
                        speaker_id,
                        tk.codec_pad_id,
                        tk.codec_bos_id,
                    ],
                    &[1, 6],
                );
                let codec_embeds = self.talker.embed_codec_ids(&codec_ids);
                let zeros = mlxcel_core::zeros(&[1, 3, hidden], embed_dtype);
                let codec_hidden = mlxcel_core::concatenate(&zeros, &codec_embeds, 1);

                parts.push(mlxcel_core::add(&text_hidden, &codec_hidden));

                trailing_text_hidden = Some(if n > 4 {
                    let rest = mlxcel_core::slice(&ah, &[0, 4, 0], &[1, n, hidden]);
                    mlxcel_core::concatenate(&rest, &tts_eos_embed, 1)
                } else {
                    mlxcel_core::copy(&tts_eos_embed)
                });
            } else {
                return Err(format!(
                    "Unexpected role token {role} after <|im_start|> (expected system/user/assistant)"
                ));
            }
        }

        let trailing_text_hidden = trailing_text_hidden.ok_or_else(|| {
            "No assistant segment found in the prompt; speech output requires a chat-templated \
             generation"
                .to_string()
        })?;
        if parts.is_empty() {
            return Err("No talker-conditioning segments found in the prompt".to_string());
        }

        let mut talker_input = mlxcel_core::copy(&parts[0]);
        for part in &parts[1..] {
            talker_input = mlxcel_core::concatenate(&talker_input, part, 1);
        }

        let sampling = &self.cfg.sampling;
        let frames = self.talker.generate_codes(
            &talker_input,
            &trailing_text_hidden,
            &tts_pad_embed,
            max_frames.unwrap_or(sampling.max_frames),
            sampling.temperature,
            sampling.top_p,
        );
        if frames.is_empty() {
            return Err(
                "The talker emitted codec EOS before producing any frames; sampling is \
                 stochastic, so retrying may succeed"
                    .to_string(),
            );
        }

        let samples = self.code2wav.decode_chunked(&frames)?;
        Ok(SpeechOutput {
            samples,
            frames: frames.len(),
            sample_rate: SPEECH_SAMPLE_RATE,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::role_segments;

    const IM_START: i32 = 151_644;

    #[test]
    fn segments_split_at_im_start_and_extend_to_generated_end() {
        // <|im_start|>system ... <|im_start|>user ... <|im_start|>assistant\n
        let prompt = [
            IM_START, 8948, 198, 100, 101, IM_START, 872, 198, 200, 201, 202, IM_START, 77091, 198,
        ];
        // 5 generated answer tokens follow the 14 prompt tokens.
        let segments = role_segments(&prompt, prompt.len() + 5, IM_START);
        assert_eq!(segments, vec![(0, 5), (5, 11), (11, 19)]);
        // The assistant segment spans its header plus the generated answer.
        let (start, end) = segments[2];
        assert_eq!(end - start, 3 + 5);
    }

    #[test]
    fn no_im_start_yields_no_segments() {
        let prompt = [1, 2, 3, 4];
        assert!(role_segments(&prompt, 10, IM_START).is_empty());
    }

    #[test]
    fn im_start_only_in_generated_tokens_is_ignored() {
        // The reference scans input_ids (the prompt) only; an <|im_start|>
        // that the model happens to generate must not open a new segment.
        let prompt = [IM_START, 872, 198, 300];
        let segments = role_segments(&prompt, 12, IM_START);
        assert_eq!(segments, vec![(0, 12)]);
    }
}
